### ISSUE TITLE
１０２１　北宮福井本線

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#101]
地域応援課　三宅
修正お願いします。
[1021　北宮福井本線　北.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10463117/1021.pdf)
[1021　北宮福井本線　南.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10463118/1021.pdf)

**Comment by isupport-kitta** [comment]
右側の開渠は種別、幅員不明でよろしかったですか。
![image](https://user-images.githubusercontent.com/110583661/213655860-a6cfbc00-ce95-4086-ac8f-91932f2d44b9.png)

**Comment by isupport-kitta** [comment]
こちらも右側の開渠は不明でよろしかったでしょうか。
![image](https://user-images.githubusercontent.com/110583661/213657951-d7206037-9655-4726-ac6b-8d68061f002d.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
北側・南側ともに　開渠　U0.4　でお願いします

**Comment by isupport-kitta** [comment]
修正をしました。ご確認お願いします。
![image](https://user-images.githubusercontent.com/110583661/213948912-72cad9f6-82e1-46d2-8ef8-a5157fa09875.png)
![image](https://user-images.githubusercontent.com/110583661/213948924-631a8a00-a2e8-4e2b-8009-8642bd8bb3af.png)

**Comment by city-soja-chiiki** [comment]
修正ありがとうございました。
