### ISSUE TITLE
道路網図の公開を行いたいのですが　2023-02-01　日付

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#106]
道路網図の公開を行いたいのですが，一度2023-02-01できれいに見えるようにお願いします。
さしあたり国道関連で修正した認定適用外網図が未供用です，三宅君にも言っておきますが，出来るところからおねがいします。
また，不要なものは廃止，短縮等するものは短縮でお願いします。
![image](https://user-images.githubusercontent.com/86514652/215949779-fa56a890-f20c-4381-8f7f-51c6d2fc8179.png)
![image](https://user-images.githubusercontent.com/86514652/215948684-0ed897ab-d868-4202-a7dc-cc7a9055e17a.png)

**Comment by yamamoto-ryuzo** [comment]
取得日不明の線もいくつかあるようです。
精査お願いします。
![image](https://user-images.githubusercontent.com/86514652/215951006-2ff50e37-5808-43f4-81eb-d71165643920.png)

**Comment by isupport-kitta** [comment]
先ほど三宅様よりご連絡いただいた件で修正を行いました。
農道10-6000番台路線の起点終点の変更、路線の短縮、分断される路線の新規発番（10-6578）
準道も国道にかかる箇所は消去日の入力および起点の変更を行いました。
また先のコメントでいただいている取得日不明と思われる側溝は側溝のスタイル「取得日不明」のフィルタが外れていることによるものかと思われます。
市道外の側溝は背景図へ変換し整備しました。

確認をよろしくお願いします。（2023-02-01）
![image](https://user-images.githubusercontent.com/110583661/215967690-53dcf765-93a2-4be4-8d48-ed08c6d6c5a2.png)
