### ISSUE TITLE
本業務進捗報告とお願い

### ISSUE THREAD

**Issue by nagasawajun** [city-soja-chiiki/douro_daityou_hosei#107]
現時点（1/30）での実績を取りまとめてみました。
 ■現時点の進捗報告
 総社市\更新データ総社市道路台帳補正実施報告書（入札業者）20230130.xlsx
実施報告書 (R4清算)シートのご確認お願いします。 

以下の修正作業については、かかったであろう日数をH列に直接手入力しております。
・認定路線資料修正・道路区域の決定(変更)報告書修正・供用の開始（廃止）報告書修正 

数量の計上の仕方で不具合がありましたら教えてください。

■お願い
お願いなのですが、180号関連だけで実施報告書 (R4清算)シートの日数と別に+25人日くらい費やしているのですが、どこかに見込ませていただくことはできないでしょうか。 

■次年度業務に向けて
それから、
　1車線道路・道路区域幅員10ｍ程度以下　  1.140人　
　2車線道路・道路区域幅員20ｍ程度以下             2.280人
についても、
180号関連以外で、1.5倍くらいの日数がかかっていそうです。次年度業務の際に少し見直していただけると幸いです。 
どうぞよろしくお願いいたします。

**Comment by yamamoto-ryuzo** [comment]
現在，QGISエクセル連携を順次開始しております。
上記３件順次対応・相談したいと思っております。今しばらくお待ちください。
特に，180号はできる限り歩掛新設で対応予定です。

**Comment by nagasawajun** [comment]
ありがとうございます。何卒よろしくお願いいたします。
既設道路入力についてはできる限り進めさせていただきます。

**Comment by yamamoto-ryuzo** [comment]
現在，ある程度自動で積算ができるようにエクセルシート
\\soja\総社市\道路台帳平面図管理システム\実施報告書
に作成中です。
で，トレースしてもらった路線ですが，どこかに判断できる属性入力してます？
納品年月日をチェックのキーにしようとおもったのですが，どうも入力されていない箇所も多いようです。

**Comment by isupport-kitta** [comment]
お世話になります。
台帳図よりトレースした路線について、判断できる属性の入力は現在しておりません。
既設道路の整備において道路基本情報レイヤは図形の入力のみで属性は変更をしておりません。
現状-R03実績で算出しております。

**Comment by yamamoto-ryuzo** [comment]
了解です！
無駄な入力がなくていいかもしれません！
ナイスです。

**Comment by nagasawajun** [comment]
お忙しいところ度々申し訳ございません。
今年度業務の工期がR5/3/31ですので、そろそろ請求書を準備したほうがよいのかなと思っております。
一宮バイパスの歩掛等検討事項が色々ありそうなので、先に請求書を作成させていただてよろしいでしょうか。
（請求金額は税込み金額5,761,800円でよろしいでしょうか。）
その他の数量を取りまとめた報告書などの完成書類は年度明けに改めて作成でもよろしいでしょうか。
今年度の弊社の出来高としては一宮バイパスを別途みていただけるとのことでしたので、おそらく予算オーバーしていると思いますので、予算に合わせて出来高を調整することになるかと思います。（一部次年度へ送る）
どうぞよろしくお願いいたします。

**Comment by yamamoto-ryuzo** [comment]
> 今年度業務の工期がR5/3/31ですので、そろそろ請求書を準備したほうがよいのかなと思っております。
> 一宮バイパスの歩掛等検討事項が色々ありそうなので、先に請求書を作成させていただてよろしいでしょうか。
> （請求金額は税込み金額5,761,800円でよろしいでしょうか。）

　請求書を作成するために，内訳が必要となります。
　今回から，作成した内容をエクセル出力し請求書を作成できるまでのシステムを構築中です。
　その後の請求でお願いします。

　ちなみに，金額は変更なしの　請求金額は税込み金額5,761,800円　を予定しております。

　いずれにせよ，今しばらくお待ちください。
　なお，他の報告書もGISからエクセル出力できるように順次システム構築予定です。

**Comment by nagasawajun** [comment]
返信ありがとうございます。
請求書作成システムについても構築ありがとうございます。
ご連絡をお待ちしております。

**Comment by nagasawajun** [comment]
お忙しいところ、何度も書き込みを申し訳ございません。
こちらについてもご連絡をお待ちしております。

**Comment by nagasawajun** [comment]
お世話になっております。こちらは請求書作成システムをお待ちしておいてよろしいでしょうか。
総社市道路・水路台帳システム基盤保守点検業務の請求書等は明日提出いたします。

**Comment by yamamoto-ryuzo** [comment]
明日頑張って作ります・・・

**Comment by nagasawajun** [comment]
返信ありがとうございます。ご無理申し上げ大変申し訳ございません。何卒宜しくお願い致します。

**Comment by yamamoto-ryuzo** [comment]
\\soja\総社市\道路台帳平面図管理システム\実施報告書
総社市道路台帳補正実施報告書R04.xlsx
をご確認ください。
良ければ，そのまま切り取って報告書ファイルとして納品ください。
１．デジタル化は延長調整しています。
　いろいろやっていると納品年月日入れないといけないような気がします。
　順次調整します。
２．農道台帳は別途　計上します。
３．納品時には，議案等に作成したものを印刷して添付ください。
　基本情報は，昨年いんさつしてもらったようにしてほしいのですが。
　納品年度がないので，出力わけができていません。
　今年度はなしでＯＫです。
４．システムからの報告書自動出力は時間が間に合わなかったので，今回は雛形作成までとしました。
　順次調整したいと思います。
以上。
