### ISSUE TITLE
道路台帳平面図の公開を行いたいのですが　2023-02-01　日付

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#108]
一度旧台帳消去の処理をきちんとお願いできませんでしょうか。
完成次第　こちらも公開します。
![image](https://user-images.githubusercontent.com/86514652/216204469-54a79992-e110-4efc-8365-677bbeb2aa89.png)

**Comment by isupport-kitta** [comment]
お世話になります。
旧台帳消去のレイヤの見直しをしました。
メッシュの一部のみマスクが入る箇所（区域認定などで一部しか整備していない）の取得日はその各供用開始日に
その他メッシュ毎のマスクは取得日を2021/04/08にて整備しております。
現在、図郭E5-242を整備中です。（旧台帳消去が入っていません。）
![image](https://user-images.githubusercontent.com/110583661/216249715-f42b8576-9241-4fec-a5ca-76e2e75b5949.png)
![image](https://user-images.githubusercontent.com/110583661/216249924-43f7b402-d224-4dfd-97b1-cb335aba9a5d.png)

**Comment by yamamoto-ryuzo** [comment]
日曜日に平面図を出力しようと思います。
その時点では、一度「旧台帳消去」を完全にしておいていただけないでしょうか。

**Comment by isupport-kitta** [comment]
金曜日までに入力が済んだ箇所のマスクをしておきます。
その際、旧台帳消去レイヤの一覧を作成しますので確認をお願いします。
よろしくお願いします。

**Comment by yamamoto-ryuzo** [comment]
マスクは取得日を2021/04/08の一択でOKです。
消しているのは2021/04/08のデータなので。
それで、うまく動作しませんか？
心の中では、day_rasterが自動で入るように設定していたつもりなのですが・・・
これも日曜日に確認します。
![image](https://user-images.githubusercontent.com/86514652/216253856-02cc1963-f606-4e6a-8538-b8abc2c86781.png)

**Comment by yamamoto-ryuzo** [comment]
マスクのレイヤ一覧不要です。
作ってくれてもたぶん、見ないので・・・

**Comment by yamamoto-ryuzo** [comment]
↑ボタン押し間違えました・・・

**Comment by isupport-kitta** [comment]
わかりました！では取得日は2021/04/08で統一しておきます。
