### ISSUE TITLE
既設道路の道路基本情報の入力時にエラーが発生する件

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#109]
お世話になります。
既設道路の道路基本情報の作図をしている際、2件ほど入力ができないものがありました。
同じ路線のほかの区間は作図できます。
路線番号01-3176　図郭E5-242 区間0700
路線番号01-3181　図郭E5-242 区間0900
下図のようなエラーが出て作図できないのですが対処の仕方のご指示をお願いします。
![image](https://user-images.githubusercontent.com/110583661/216276868-031aeb10-9756-45e4-9b0d-661499ec4237.png)

![image](https://user-images.githubusercontent.com/110583661/216276734-8366ceb7-41cd-4c9d-8d17-9af709d4f194.png)

**Comment by yamamoto-ryuzo** [comment]
先ほど確認しました。
エラーのとおり同一点でラインを作成したのだと思います。
検索すると点の状態で線が登録されていると思われます。
一度，部分地物の削除でこの点を削除して，再作図してみてください。
![image](https://user-images.githubusercontent.com/86514652/217160927-54246f50-7dcb-429d-8e99-3b442fa3acbe.png)

**Comment by yamamoto-ryuzo** [comment]
間違って，属性を削除しないように，ジオメトリだけを削除してください。

**Comment by isupport-kitta** [comment]
ありがとうございます。
修正できました。
