### ISSUE TITLE
路線網図の再確認　　基本は　認定（未供用）　＞　供用開始　です。

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#111]
路線網図の再確認　　基本は　認定（未供用）　＞　供用開始　です。

1.第一段階
　認定　基本未供用で作図です。
　同日供用開始　　　供用開始で作図です。

2.第二段階
　認定日とは別日に供用開始
　供用開始日に未供用は　消去年月日　を入力
　新たに、供用開始で作図　取得年月日　を入力

です。

↓修正お願いします。
その他も確認お願いします。

こちらでもエラー処理を考えます。

![image](https://user-images.githubusercontent.com/86514652/216918129-5ef65c87-0771-4039-ba5c-6e46e82005d5.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。
見直しをします。

**Comment by isupport-kitta** [comment]
2022/03以降に路線認定したものにつきまして、見直しを行いました。
未供用が作図されていなかったり、路線情報のかけがありましたので修正しました。
ご確認よろしくお願いします。
