### ISSUE TITLE
10-5043　内容確認

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#112]
この路線供用開始してないのでは？
もう一度認定から確認ください。
![image](https://user-images.githubusercontent.com/86514652/216954150-049901bb-d0e4-4bb4-836d-10dacd3c288a.png)

**Comment by isupport-kitta** [comment]
お世話になります。
10-5043路線　小寺380-1について
10/18にお伺いしたときに認定路線の作成のご依頼を受け路線変更を作成しました。
![image](https://user-images.githubusercontent.com/110583661/217111185-0051fccf-6c9d-4f3a-afb3-cabb44dad13f.png)

"\\soja\総社市\更新データ\議案用\R04\12月議会\議案（路線認定）\R4.11 路線変更_pagenumber.pdf"

供用はしておりません。
なので現状の路線網図の中の情報が元の路線網図のままになっているのが原因かと思われます。
未供用に修正して路線変更の情報を追加しておきます。申し訳ありません。

**Comment by yamamoto-ryuzo** [comment]
変わった部分のみが，供用開始の告示していないので未供用です。
もともと供用開始していた個所は供用です。
![image](https://user-images.githubusercontent.com/86514652/217157817-3a0c7a9e-8d0e-402f-9518-01af9a3a91cc.png)

**Comment by yamamoto-ryuzo** [comment]
平面図の削除ができていません。
変更と同時に，変更した区域は自動的に区域の廃止となります。
が，その作業は必要です。
![image](https://user-images.githubusercontent.com/86514652/217159381-2beda2d2-bb49-4dcf-87b1-37c4d738e6d8.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。2022/12/28で消去年月日をいれました。
また、路線認定は変更部分のみ未供用にしました。
![image](https://user-images.githubusercontent.com/110583661/217393512-4ec5cee0-364c-4ea0-a783-e4c03a561301.png)

**Comment by yamamoto-ryuzo** [comment]
認定日が違いませんか？
![image](https://user-images.githubusercontent.com/86514652/217416382-70c2edb0-1b74-4aad-9c58-a3c0e24ef4b0.png)
