### ISSUE TITLE
道路網図　未供用・供用のマニュアルの追加及び表示厳格化について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#113]
マニュアル追加しました。
![image](https://user-images.githubusercontent.com/86514652/217417188-c47997f6-95e5-43be-a968-339fe48bb581.png)

**Comment by yamamoto-ryuzo** [comment]
表示の厳格化を行いました。
未供用なのに供用開始日が入っていればエラー表示としました。
![image](https://user-images.githubusercontent.com/86514652/217431336-ff695019-1db0-4b17-821a-32504eb560eb.png)

**Comment by yamamoto-ryuzo** [comment]
網図の見直しは，「道路網図作成」を「路線網図見直し」として計上ください。
![image](https://user-images.githubusercontent.com/86514652/217432637-85cb5690-a524-4fc4-887a-6cac0a5f597c.png)
どうも，36路線あるようです。確認の上，供用開始年月日と起点，終点を削除してください。
![image](https://user-images.githubusercontent.com/86514652/217433191-64f7dde5-83ed-47aa-a1cd-dc56eaa8e92b.png)

**Comment by yamamoto-ryuzo** [comment]
このあたりが，修正出来次第再度，再公開し直します。

**Comment by isupport-kitta** [comment]
36件確認しました。
![image](https://user-images.githubusercontent.com/110583661/217436904-9aaaa21f-1377-4f2a-9547-acccd782638d.png)
黄色のラインより上の路線は消去日がはいっておらず、単に供用なのに未供用になっているだけなのか、理由があって未供用にしているが誤って供用開始日が入っているのかがわかりません。
供用開始日を削除することで対応してよろしいですか。
![image](https://user-images.githubusercontent.com/110583661/217437509-53aa0ee8-4bdf-4f49-b60d-a2931b19119f.png)

**Comment by yamamoto-ryuzo** [comment]
古い路線は，単純に未供用の場合が多いです。
しかし，位置を確認して，背景に平面図が描かれているかどうかを確認して，削除でお願いします。
それ以外の場合は，想定外です。
ご連絡ください。

**Comment by isupport-kitta** [comment]
ありがとうございます。
現状、路線は未供用、消去日なし、供用開始日が入っています。

確認
・背景図に路線が描かれている場合→連絡(新たにissues立ち上げます）
・背景図から路線が未供用とわかる場合
路線は消去日に日付（本日でよろしいですか。）を入力、供用開始年月日はNULLにする。

この対応でよろしいですか。

**Comment by isupport-kitta** [comment]
調べてみました。
![image](https://user-images.githubusercontent.com/110583661/217449849-2ca7d3c7-a29f-4670-8b21-45db52f71c20.png)

**Comment by isupport-kitta** [comment]
路線の一部が未供用の箇所は供用開始年月日をnullにしてそのままの方がよろしいですか。
消去年月日を入力した方がよいでしょうか

**Comment by yamamoto-ryuzo** [comment]
> ありがとうございます。 現状、路線は未供用、消去日なし、供用開始日が入っています。
> 
> 確認 ・背景図に路線が描かれている場合→連絡(新たにissues立ち上げます） ・背景図から路線が未供用とわかる場合 路線は消去日に日付（本日でよろしいですか。）を入力、供用開始年月日はNULLにする。
> 
> この対応でよろしいですか。

　だめです。
　表示をやめたわけでなく，未供用で表示すべきところが，一部供用している関係でおそらく，供用開始年月日が入っていると思われます。
　今回の厳格化（ルール変更）を行わなければ，問題が発生しなかったものとなります。
　なので，当初の指示通り
![image](https://user-images.githubusercontent.com/86514652/217471100-5c987f33-3f18-447b-823d-7ac02d8b575a.png)
　でお願いします。
　また，根本的に，脈絡のない日にちで年月日を入力することはあり得ません。

**Comment by yamamoto-ryuzo** [comment]
![image](https://user-images.githubusercontent.com/86514652/217471583-74e5003c-e5a1-405f-bfac-defab846d6f6.png)
これは，議案で廃止していたということでしょうか？？？
以上。

**Comment by yamamoto-ryuzo** [comment]
![image](https://user-images.githubusercontent.com/86514652/217471946-9c3b9bdb-fb55-49ff-a0a4-ce4e253be793.png)
これらは，当該網図の範囲内が未供用であったということでよかったでしょうか。
網図の作図区間が未供用なら，
同じく，
![image](https://user-images.githubusercontent.com/86514652/217472579-07a12a10-b4d6-42de-84ab-cf98fc6134a7.png)
でお願いします。
GISでは
![image](https://user-images.githubusercontent.com/86514652/217472901-6e90eb4b-b00d-47c2-b385-14dba79b1a29.png)
の右側３項目です。

**Comment by isupport-kitta** [comment]
> ![image](https://user-images.githubusercontent.com/86514652/217471583-74e5003c-e5a1-405f-bfac-defab846d6f6.png) これは，議案で廃止していたということでしょうか？？？ 以上。

この2路線は2021-12-28の議案で廃止路線になっていました。
その他の路線は供用開始年月日の削除を行います。

**Comment by isupport-kitta** [comment]
その他の路線（14路線）は供用開始年月日の削除を行います。

**Comment by yamamoto-ryuzo** [comment]
> > ![image](https://user-images.githubusercontent.com/86514652/217471583-74e5003c-e5a1-405f-bfac-defab846d6f6.png) これは，議案で廃止していたということでしょうか？？？ 以上。
> 
> この2路線は2021-12-28の議案で廃止路線になっていました。 その他の路線は供用開始年月日の削除を行います。

確認しました。
区域の廃止ですね！
路線の廃止ではありません。
区域の廃止に伴う，供用＞未供用への変更です。
なので，
![image](https://user-images.githubusercontent.com/86514652/217679473-250a5ccf-595b-4c94-817f-8ed2e06a56bc.png)

**Comment by yamamoto-ryuzo** [comment]
> その他の路線は供用開始年月日の削除を行います。

NULLにするのは３項目です。
![image](https://user-images.githubusercontent.com/86514652/217680132-9487f850-2881-444b-be5a-af466f9925f2.png)

**Comment by isupport-kitta** [comment]
> > > ![画像](https://user-images.githubusercontent.com/86514652/217471583-74e5003c-e5a1-405f-bfac-defab846d6f6.png)これは，議案で廃止していたということでしょうか？？？ 以上。
> > 
> > 
> > この2路線は2021-12-28の議案で廃止路線になっていました。 その他の路線は供用開始年月日の削除を行います。
> 
> 確認しました。 区域の廃止ですね！ 路線の廃止ではありません。 区域の廃止に伴う，供用＞未供用への変更です。 なので， ![画像](https://user-images.githubusercontent.com/86514652/217679473-250a5ccf-595b-4c94-817f-8ed2e06a56bc.png)

すいません。路線廃止と勘違いしてました。
区域の廃止だけ→未供用なんですね。
42-5002
42-5026
について管理区分を「路線認定」にもどしたのですが、路線認定タブの議決内容の項目をnullに戻すことができませんでした。設定でnullが選択できないようになっているので変更をお願いしてよろしいでしょうか。お手数をおかけします。申し訳ありません。

**Comment by isupport-kitta** [comment]
> > その他の路線は供用開始年月日の削除を行います。
> 
> NULLにするのは３項目です。 ![画像](https://user-images.githubusercontent.com/86514652/217680132-9487f850-2881-444b-be5a-af466f9925f2.png)

承知しました。

**Comment by yamamoto-ryuzo** [comment]
> すいません。路線廃止と勘違いしてました。
> 区域の廃止だけ→未供用なんですね。
> 42-5002
> 42-5026
> について管理区分を「路線認定」にもどしたのですが、路線認定タブの議決内容の項目をnullに戻すことができませんでした。設定でnullが選択できないようになっているので変更をお願いしてよろしいでしょうか。お手数をおかけします。申し訳ありません。

対応できるようにしておきました。
併せて，「区域変更等（議決不要）」と「等」を追加したので，議決不要な路線網図の変更はこちらを選択してください。

**Comment by yamamoto-ryuzo** [comment]
追伸，結構プロジェクトファイル更新しています。
必ず，プロジェクトファイルを再読み込みした後に，上記作業は行ってください。
以上。

**Comment by isupport-kitta** [comment]
ありがとうございます。議決内容を変更しました。
![image](https://user-images.githubusercontent.com/110583661/218640250-9079241b-a5fd-4306-934c-b5ed88d76d32.png)
