### ISSUE TITLE
年月日の入力について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#114]
どうも勝手気ままな日にがいつの間にか入力され始めております。
２０２３-０１-３１日に廃止の議決はされていないと思います。
とりあえず，これを入力した原因はなんでしょうか？
![image](https://user-images.githubusercontent.com/86514652/217728548-9b7694c1-93ea-49d9-a9ea-7c9aa5bd2156.png)

**Comment by yamamoto-ryuzo** [comment]
路線認定ももう少し厳格化しようと思います。
作業の都合上
２０２２／１２／２８　＞　１９８７／３／３１　にこちらで修正しておきます。
![image](https://user-images.githubusercontent.com/86514652/217735839-a507750e-a1d6-481c-9ebb-7be72b9e86a4.png)

**Comment by yamamoto-ryuzo** [comment]
作業の都合上　供用開始日を　
１９８７／３／３１　＞　２０２３／１／２９　にこちらで修正しておきます。
取得した日に供用開始しているはずです。
![image](https://user-images.githubusercontent.com/86514652/217742809-a4782815-075c-4f95-abbf-7cb348a2f7b5.png)
![image](https://user-images.githubusercontent.com/86514652/217743307-c45ac5e7-b6ba-4850-b3ac-00d3797f14b1.png)

**Comment by yamamoto-ryuzo** [comment]
この路線，なぜこんなことにと思いましたが，そもそも路線変更の議決をしておりませんでした。
なので，そもそも，このシステムが今回のような路線変更を伴わない，路線網図の変更に対応しておりませんでした。
マニュアル再整備して，再度ご連絡いたします。

**Comment by isupport-kitta** [comment]
ありがとうございます。
10-3227のように路線変更はないが区域変更により路線網図の形状および情報が変更になる場合の対処の仕方等のマニュアル追加等、大変助かりました。

また、下記の件も申し訳ありませんでした。

> どうも勝手気ままな日にがいつの間にか入力され始めております。 ２０２３-０１-３１日に廃止の議決はされていないと思います。 とりあえず，これを入力した原因はなんでしょうか？ ![image](https://user-images.githubusercontent.com/86514652/217728548-9b7694c1-93ea-49d9-a9ea-7c9aa5bd2156.png)

すいません、10-5159は12月の決議で廃止路線になっているので「2022-12-28」が正しいです。
修正しました。
![image](https://user-images.githubusercontent.com/110583661/218642039-a1697585-e369-4890-bdc7-1628e1067754.png)
