### ISSUE TITLE
区域変更（議決不要）路線網図の見直しについて

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#116]
路線認定（道路網図）の区域変更（議決不要）の路線をマニュアルに基づいと見直しをおねがいします。
網図の見直しは，「道路網図作成」を「路線網図（区域変更（議決不要））見直し」として計上ください。
積算も補足を追加しました。
![image](https://user-images.githubusercontent.com/86514652/217989605-d6b52f49-ff85-44e6-894c-7e106b234883.png)
こちらを先に作業していただいて，現在進行の作業の確認に戻ります。

**Comment by yamamoto-ryuzo** [comment]
確認したところ　１０－３２２７　一路線でしたので，この一路線の処理をお願いいたします。

**Comment by isupport-kitta** [comment]
お世話になります。
路線網図の見直しについて本日より作業いたします。
質問等ありましたらまたこちらにご連絡させていただきます。
よろしくお願いします。
