### ISSUE TITLE
R5.3.31　告示文章修正依頼について

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#117]
地域応援課　三宅

お世話になっております。　R5.3.31告示文章の修正依頼の件です。

〇区域決定
〇区域変更

ご確認の上、修正お願いします。

区域決定
[区域決定.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10788637/default.pdf)

区域変更
[区域変更.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10788640/default.pdf)

**Comment by isupport-kitta** [comment]
お世話になります。18条管理網図の修正および【原本】R05-03-31　区域決定・供用開始　告示○○号.xlsの修正をいたしました。
ご確認お願いします。

また、区域変更の変更前延長に区域変更箇所ではない延長（区間を分ける前の延長）が含まれていましたので、その箇所は延長を区間変更の箇所のみの延長にしております。
よろしくお願いします。

"\\soja\総社市\更新データ\議案用\R04\3月議会\告示（路線認定・区域決定，変更・供用開始）\【原本】R05-03-31　区域決定・供用開始　告示○○号.pdf"

**Comment by isupport-kitta** [comment]
お世話になります。
昨日、ご依頼のありました修正をいたしました。
ご確認をよろしくお願いします。
![image](https://user-images.githubusercontent.com/110583661/221714108-11710ef4-2429-4c11-9803-86bdf121a83c.png)
![image](https://user-images.githubusercontent.com/110583661/221714202-5030862b-21a3-43fe-a090-f55e8da005ba.png)
![image](https://user-images.githubusercontent.com/110583661/221714292-b44df19a-2cb6-40c3-9786-73d359fd0162.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
修正ありがとうございました。　確認します。
