### ISSUE TITLE
1011 中央本線の終点番地変更依頼について

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#118]
地域応援課　三宅

1011　中央本線の終点番地の修正をお願いします。
終点番地　総社市　三輪426番1地先　→　総社市　真壁426番1地先

編集の履歴が残るように新たに路線取得してください。
旧路線の消去日　R5.2.28
取り直し路線の取得日　R5.2.28

![1011 中央本線](https://user-images.githubusercontent.com/110579656/221740781-ca8d078c-980e-44b4-aead-9f0601c55965.jpg)

**Comment by isupport-kitta** [comment]
お世話になります。
1011　中央本線の終点番地の修正が完了しました。
ご確認をお願いします。
![image](https://user-images.githubusercontent.com/110583661/222588750-0ad363c6-9b7c-40bc-82a2-0e690c53a7cd.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
確認しました。修正ありがとうございました。
