### ISSUE TITLE
台帳毎のプロジェクトファイルの統合

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#12]
最終的に、台帳毎のプロジェクトファイルと1ファイルとしたいので、タイトルだけ残しておきます。

**Comment by isupport-kitta** [comment]
現在、作業開始する際に
"\\soja\総社市\QGIS\yr-qgis-portable-launcher\QGIS.bat"
を毎回起動し、最初のプロジェクトテンプレートを開く時に
道路台帳平面図管理システム（作業用）.qgzを選択して作業をしております。
（既設道路入力作業、目視チェック作業）

告示図面等をPDFで出すときに(管理用）を使わせていただくことがあります。

**Comment by yamamoto-ryuzo** [comment]
こちらでお願いしているシステムを利用していれば、テンプレートでの利用なので、常時　管理者用　を利用してください。

同一名称で保存しない限り問題ありません。
どちらかというと違うものを使っていたほうが問題が発生します。

そちらでの利用がなれたら　管理者用　名前は削除の予定です。
最終目標は、プロジェクトの維持管理を含めての委託なのです。

**Comment by yamamoto-ryuzo** [comment]
このファイルは残しておいたほうがいいのでしょうか？
![image](https://user-images.githubusercontent.com/86514652/197514341-79ecd4bd-3813-43a2-b806-78a58f2a7915.png)

**Comment by isupport-kitta** [comment]
作業しているものに確認しました。
上記ファイルを現在使用しているものはいませんでした。
削除よろしくおねがいします。
