### ISSUE TITLE
道が繋がっていない・・・

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#124]
下記のように，交差点部がどの路線にもなっていないものは三宅と協議の上修正願います。
優先的に繋げるのは　市道です。
![image](https://user-images.githubusercontent.com/86514652/226812285-5174de7e-b4b1-4ec9-b07d-d271f720ed90.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
10-3663　総社支線3663号道を東に延長してください。
区域変更で対応お願いします。

**Comment by isupport-kitta** [comment]
お世話になります。アイ・サポート橘田です。
先日お話しさせていただきましたように2023/06/30付けにて区域変更の作成をさせていただきました。
確認をよろしくお願いします。
![image](https://user-images.githubusercontent.com/110583661/228756326-3ada380b-6b2d-42c6-bd22-550875888e46.png)
![image](https://user-images.githubusercontent.com/110583661/228756462-91d91d95-f2f6-4534-a472-b3aa8740484d.png)
