### ISSUE TITLE
資料返却について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#128]
恐れ入りますが、お借りしている各道路の資料の返却時期に関しまして、
ご都合のよい日時をお知らせいただけますでしょうか。
よろしくお願いいたします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅

お世話になっております。
資料返却の日時ですが、4月5日（水）10：00～
よろしくお願いします。

**Comment by isupport-kitta** [comment]
ありがとうございます。
明日10:00~にお伺いします。
よろしくお願いします。

**Comment by isupport-kitta** [comment]
ありがとうございました。
