### ISSUE TITLE
QGIS3.28.5へバージョンアップ

### ISSUE THREAD

**Issue by ageno-geo** [city-soja-chiiki/douro_daityou_hosei#129]
QGIS3.28.5へバージョンアップしました。
テンプレートファイルの場所を変更しています

**Comment by yamamoto-ryuzo** [comment]
今回より，QGISのバージョンアップをGEOソリューションズさんに委託しておます。
少なくとも４回／年を予定しております。
よろしくお願いいたします。

**Comment by ageno-geo** [comment]
終了時のエラー解消しました
