### ISSUE TITLE
クラウド環境　道路台帳システムのバージョンアップについて

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#13]
本日より、プラグインのバージョン管理を追加したシステムになりました。

**Comment by yamamoto-ryuzo** [comment]
QGIS3.22.11にバージョンアップしました。
一部の解析機能等が利用可能になりました。
![image](https://user-images.githubusercontent.com/86514652/191627476-c301ddde-a8ff-4ee9-a07b-152a140c3d0e.png)
![image](https://user-images.githubusercontent.com/86514652/191627503-6f1d7bcc-d97d-47d3-bc93-0eaee739ca0b.png)

**Comment by yamamoto-ryuzo** [comment]
旧システムのバッチファイルを本日削除しました。
今後は、
\\soja\総社市\QGIS\yr-qgis-portable-launcher　
QGIS.BAT 
から起動してください。
![image](https://user-images.githubusercontent.com/86514652/192706923-6521b3e8-4771-4f79-88da-b44179fc151a.png)

**Comment by yamamoto-ryuzo** [comment]
検索プラグイン日付表示をわかりやすくしました。
システムが自動アップデートされない場合は教えて下さい。
![image](https://user-images.githubusercontent.com/86514652/193439591-4bd0bfcb-6f4a-4d27-b00c-9af49c5aeab4.png)

**Comment by yamamoto-ryuzo** [comment]
スレッドが長くなるので，バージョンアップごとに立ち上げに変更します。
