### ISSUE TITLE
クラウドサーバ保守について

### ISSUE THREAD

**Issue by nagasawajun** [city-soja-chiiki/douro_daityou_hosei#133]
以下の2点確認お願いします。
Cドライブの残容量が、30GB程度となっております。消してもよいファイルがありましたら教えてください。
バックアップについて、
バックアップはできていそうですが、カウント中にエラーとなっております。
問題ないか確認お願いいたします。
以下に本日のバックアップログをPDFで保管しております。
\\Soja\総社市\市役所⇔アイ・サポート
log.pdf

**Comment by yamamoto-ryuzo** [comment]
とりあえず、キャッシュ等の不要なファイルを削除しておきました。
残容量が40GB程度に増えています。
Hyper-Vで利用している容量やデータ領域の要領も不足気味のようです。
本年度の保守業務契約が激しく遅れているようですので、併せて補強して契約するようにします。
しばらくお待ちください。

**Comment by nagasawajun** [comment]
三宅様
お世話になっております。
これに関連するメールを9/24と10/4（再送）にお送りしておりますのでご確認いただけましたら幸いです。

**Comment by nagasawajun** [comment]
@yamamoto-ryuzo さま
今年度業務でSSD1TBを購入するのですが、製品の指定予定とかなかったでしょうか。
なければ、以下の製品にしておこうかなと思います。
https://item.rakuten.co.jp/kasuikasui/5000000011957/

**Comment by yamamoto-ryuzo** [comment]
@nagasawajun 
保守契約できたのですね。
よかったです。

サーバも、新庁舎建て替え時に一新予定で、その中にブレードとして移設になるはずなのですが、保守は担当課ということになれば、引き続きLGWANの保守のお願いすることになると思います。

併せて、よろしくお願いいたします。
