### ISSUE TITLE
議案（路線認定）　R05-08月　について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#136]
お世話になります。本日はありがとうございました。
資料作成いたしましたのでご確認よろしくお願いします。

\\soja\総社市\更新データ\議案用\R05\9月議会\議案（路線認定）　R05-08月

**Comment by isupport-kitta** [comment]
位置図の順番の修正が完了いたしました。
ご確認をお願いします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
お世話になります。急な依頼にご対応していただき，ありがとうございました。
今年も引き続きよろしくお願いします。

**Comment by isupport-kitta** [comment]
こちらこそよろしくお願いします。
