### ISSUE TITLE
道路台帳調書作成システムのエクスポートについて

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#138]
昨年度、資料を作成させていただいた路線を対象に
\\soja\総社市\道路台帳調書作成システム\総社市道路台帳調書作成システム操作マニュアル
こちらを参照しながら道路台帳入力シートを出力をさせていただきたいのですが
出力をする時に「道路台帳管理者」にユーザー切替をしたと思います。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/70dee63f-55fe-4dc3-adbe-cd946666ab12)
こちらのパスワードを教えてください。
よろしくお願いします。

また、パスワードが非公開の場合、総社市様の方で既設対象路線を出力していただいてそれらのファイルをいただけたらと思います。
下記の構成のようなフォルダになると思います。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/e5eb78af-8234-4b0c-9ef6-a549705e0607)
よろしくお願いします。

**Comment by isupport-kitta** [comment]
8月には平面図作成もあり、次回打合せ時には作業が終了している状態にしたいので、
早急にお返事をお願い申し上げます。

**Comment by city-soja-chiiki** [comment]
パスワードはsojaとなります。
ご確認をお願いいたします。

**Comment by isupport-kitta** [comment]
> パスワードはsojaとなります。 ご確認をお願いいたします。

ありがとうございます。エクスポートして修正を始めます。
昨年度更新された道路を一覧にいたしました。
下記道路以外で更新がありましたらお伝えください。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/21db8afb-62ff-41c6-b1aa-a9a10cbf82ac)

一覧は"\\soja\総社市\更新データ\GIS作業記録.xlsx"の調書データ修正シートにあります。
別途作業記録が必要でしたら、お知らせください。

**Comment by isupport-kitta** [comment]
上記更新道路のエクスポートが終了いたしました。
\\soja\総社市\道路台帳調書作成システム\道路台帳調書作成システムデータ　QGIS移行\R05\Export_20230727090034

こちらのデータを元に修正をしていきます。
また、出力時に気が付いたのですが、昨年度（R03年度の道路）の修正が反映されていないように思いました。
よく見たら2020年度の状態の道路台帳データでした。

R05年度業務（データ的にR04年度の道路更新）分の修正作業は
現状（R02年度の道路までの状態）から出力したデータを修正することでよろしかったでしょうか。

**Comment by yamamoto-ryuzo** [comment]
マニュアル更新しておきました。
\\soja\総社市\マニュアル\道路・水路台帳　管理マニュアル 2023-07-24.docx
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/86514652/387a6ec2-9495-4f02-9727-3bf5278034be)

**Comment by yamamoto-ryuzo** [comment]
>R05年度業務（データ的にR04年度の道路更新）分の修正作業は
現状（R02年度の道路までの状態）から出力したデータを修正することでよろしかったでしょうか。

だめです。
パスコに早急に修正するように言います。

**Comment by yamamoto-ryuzo** [comment]
>一覧は"\soja\総社市\更新データ\GIS作業記録.xlsx"の調書データ修正シートにあります。
別途作業記録が必要でしたら、お知らせください。

道路基本情報の取得年月日が昨年度の期間である路線です。
エクスポートして，フィルター処理が楽です。

![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/86514652/fb34d8c5-2e95-4ec3-91e6-0cbdd3c93fb2)

**Comment by isupport-kitta** [comment]
> > 一覧は"\soja\総社市\更新データ\GIS作業記録.xlsx"の調書データ修正シートにあります。
> > 別途作業記録が必要でしたら、お知らせください。
> 
> 道路基本情報の取得年月日が昨年度の期間である路線です。 エクスポートして，フィルター処理が楽です。

ありがとうございます。
そのようにさせていただきます。
道路台帳調書システムの更新が終わりましたら、再度入力シートを出力したいと思いますので
ご連絡をいただけますと助かります。よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
> 上記更新道路のエクスポートが終了いたしました。 \soja\総社市\道路台帳調書作成システム\道路台帳調書作成システムデータ　QGIS移行\R05\Export_20230727090034
> 
> こちらのデータを元に修正をしていきます。 また、出力時に気が付いたのですが、昨年度（R03年度の道路）の修正が反映されていないように思いました。 よく見たら2020年度の状態の道路台帳データでした。
> 
> R05年度業務（データ的にR04年度の道路更新）分の修正作業は 現状（R02年度の道路までの状態）から出力したデータを修正することでよろしかったでしょうか。


先ほど、パスコよりR3年度データの修正完了の報告がありました。
ご確認をお願いいたします。

**Comment by isupport-kitta** [comment]
> 先ほど、パスコよりR3年度データの修正完了の報告がありました。 ご確認をお願いいたします。

ご連絡ありがとうございます。
確認させていただいたのち入力シートを出力いたします。
よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
パスコより、一部の路線についてエラーがあったとのことです。
ご確認をお願いいたします。

以下、パスコからのメール抜粋します

１．昨年度の検収で更新対象路線が間違ってた件で、
　今回の補正で訂正されるとのことでお伺いしていましたが、
　誤っていた路線No.2014、及び正しい路線No.2041についての
　更新データが入っておりません。
　どのように取り扱いを行うのかご回答お願いします。
　※このままのデータだと昨年度の誤りが是正されないままとなります。

２．以下のエラーがありますのでお手数ですがご確認お願いいたします。
①以下の新規・更新路線の情報について
　路線情報に存在していますが、区間情報に存在していません。

路線番号　路線名称
10-3655　総社支線３６５５号道
10-3666　総社支線３６６６号道
10-5043　小寺支線５０４３号道
10-5057　福井支線５０５７号道
10-5158　福井支線５１５８号道
12-3474　真壁支線３４７４号道

②以下の廃止路線について、区間情報に情報が残っている。
こちらは、当方で削除しても構いません。
10-5159　刑部支線５１５９号道
12-3071　真壁支線３０７１号道
12-3072　真壁支線３０７２号道
12-3073　真壁支線３０７３号道
12-3074　真壁支線３０７４号道
17-5019　富原支線５０１９号道

**Comment by isupport-kitta** [comment]
お世話になります。
各項目にて確認と対処をお伺いさせてください。

> １．昨年度の検収で更新対象路線が間違ってた件で、 　今回の補正で訂正されるとのことでお伺いしていましたが、 　誤っていた路線No.2014、及び正しい路線No.2041についての 　更新データが入っておりません。 　どのように取り扱いを行うのかご回答お願いします。 　※このままのデータだと昨年度の誤りが是正されないままとなります。

当該路線の道路台帳入力シートをDLし、現状のQGISとの違いを抜粋、道路台帳入力シートを修正（更新）し提出。

> ２．以下のエラーがありますのでお手数ですがご確認お願いいたします。 ①以下の新規・更新路線の情報について 　路線情報に存在していますが、区間情報に存在していません。
> 
> 路線番号　路線名称 10-3655　総社支線３６５５号道 10-3666　総社支線３６６６号道 10-5043　小寺支線５０４３号道 10-5057　福井支線５０５７号道 10-5158　福井支線５１５８号道 12-3474　真壁支線３４７４号道

・2023-03-31時点で変更なしの路線(2023-09-29で区域変更）
10-5043、10-5057、10-5158
・2023-03-31時点で路線認定のみされており、区間情報がない状態であった路線(2023-09-29で区域認定）
10-3655、10-3666、12-3474
 上記路線群は2023-09-29に更新がされるもので、路線の情報の更新が不要であったと思われます。
すいません、修正に使用したデータに2023-09-29のものが混ざってしまっていたのが原因と思われます。
今後はこのようなことがないように気を付けます。
確認です。
路線認定のみされていて区域認定がされていない路線は新規路線としての登録は不要でよろしかったですか。

> ②以下の廃止路線について、区間情報に情報が残っている。 こちらは、当方で削除しても構いません。 10-5159　刑部支線５１５９号道 12-3071　真壁支線３０７１号道 12-3072　真壁支線３０７２号道 12-3073　真壁支線３０７３号道 12-3074　真壁支線３０７４号道 17-5019　富原支線５０１９号道

　確認です。
道路台帳平面図管理システムにて消去日を入力した道路基本情報（区間情報）は「削除」とすればよろしいですか。
上記路線は全て廃止路線ですので削除していただきたいです。


以上、よろしくお願いします。

**Comment by isupport-kitta** [comment]
お世話になります。
昨年度の更新対象路線が間違っていた件の路線2014と路線2041の更新データを作成しました。
"\\soja\総社市\道路台帳調書作成システム\道路台帳調書作成システムデータ　QGIS移行\R05\提出用\20230927\Export_20230927084730"

上記箇所に置かせていただいております。
確認をお願いします。

**Comment by city-soja-chiiki** [comment]
> ・2023-03-31時点で変更なしの路線(2023-09-29で区域変更） 10-5043、10-5057、10-5158 ・2023-03-31時点で路線認定のみされており、区間情報がない状態であった路線(2023-09-29で区域認定） 10-3655、10-3666、12-3474 上記路線群は2023-09-29に更新がされるもので、路線の情報の更新が不要であったと思われます。 すいません、修正に使用したデータに2023-09-29のものが混ざってしまっていたのが原因と思われます。 今後はこのようなことがないように気を付けます。 確認です。 路線認定のみされていて区域認定がされていない路線は新規路線としての登録は不要でよろしかったですか。
> 
道路台帳調書に関しては、区域決定（変更）、供用開始まで至った路線のみが反映対象となります。
認定のみされている路線に関しては、計画段階で道路が完成していない状態となるため、対象外となります。

> > ②以下の廃止路線について、区間情報に情報が残っている。 こちらは、当方で削除しても構いません。 10-5159　刑部支線５１５９号道 12-3071　真壁支線３０７１号道 12-3072　真壁支線３０７２号道 12-3073　真壁支線３０７３号道 12-3074　真壁支線３０７４号道 17-5019　富原支線５０１９号道
> 
> 　確認です。 道路台帳平面図管理システムにて消去日を入力した道路基本情報（区間情報）は「削除」とすればよろしいですか。 上記路線は全て廃止路線ですので削除していただきたいです。
> 
> 以上、よろしくお願いします。

調書作成システム上、廃止した路線の区間情報が残っているとエラーで処理にストップがかかってしまうため、削除していただいて問題ありません。
上記路線に関しては、シート上からの削除を依頼しておきます。

**Comment by isupport-kitta** [comment]
回答ありがとうございます。
よろしくお願いします。
