### ISSUE TITLE
プロジェクト毎の検索検索機能について

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#14]
プロジェクト毎に専用の検査機能を追加できるようになりました。
https://github.com/yamamoto-ryuzo/GEO-search-plugin
検索したい　レイヤ+属性、検索に項目を制限し表示したい場合はその項目　をこちらに投稿してください。
（設定例）
    {
      "Title": "地籍検索(地番)",
      "Layer": {
        "LayerType": "Name",
        "Name": "地籍",
        "Encoding": "cp932"
      },
      "SearchField": {
        "FieldType": "Text",
        "ViewName": "住所",
        "Field": "住所"
      },
      "ViewFields": []
    }

**Comment by yamamoto-ryuzo** [comment]
道路網図管理システムに検索機能を追加しました。
こんな感じで検索できるようになります。
必要な検索があれば、
レイヤ名、検索対象の属性名、表示したい属性名をこちらへ投稿ください。
![image](https://user-images.githubusercontent.com/86514652/192143669-e65bea02-9437-4274-aefa-ef869954785d.png)

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/31
へプラグイン関連を統一します。
