### ISSUE TITLE
正しいプロジェクトファイルの位置について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#148]
@nagasawajun 
いつからかは不明ですが，正しいプロジェクトファイルの位置がおかしくなっています。
https://github.com/city-soja-chiiki/QGIS_maintenance/issues/11
にて，確認をお願いしておりますが，違うプロジェクトファイルで操作すると異なった結果になります。
本来は現在
　\\soja\総社市\道路台帳平面図管理システム\プロジェクトファイル\3.28
を利用しているはずだったと思うのですが？
一応ご連絡します。
今後，マニュアルか何かの整備も検討します。

**Comment by isupport-kitta** [comment]
お世話になります。
確認したところ　\soja\総社市\道路台帳平面図管理システム　の直下のプロジェクトファイルを開いて作業をしていたようです。
QGIS.bat起動時の最初の画面に出てくるテンプレートになっているのが原因かと思います。

起動方法の確認を一度お願いします。　
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/d3862f60-77c8-4551-8e48-073d88d409e4)
上記上記batファイルより起動
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/7ebdd996-deb1-4a0d-b058-050bf2192dcd)
この画面の③道路台帳平面図管理システムをクリックして起動

上記の操作で作業をしております。
解決策として、初期画面に出てくるテンプレートの変更などができましたら、ご教授いただけると幸いです。
よろしくお願いします。

また、下箇所のプロジェクトファイルは変数や表示スタイルなどの変更後の保存をしてもよろしいでしょうか。
下箇所のプロジェクトファイルは市道編入等台帳や路線認定などのレイヤがなく、資料等の作成に困る状態です。
　\soja\総社市\道路台帳平面図管理システム\プロジェクトファイル\3.28\③道路台帳平面図管理システム.qgs
お手数をおかけして申し訳ありません。よろしくお願いします。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/f75a2a09-eff3-41e4-b04e-776ecdcd9577)

**Comment by yamamoto-ryuzo** [comment]
了解しました。
現在の設定で困っていなければ、とりあえずそのまま利用ください。

今月末で総社市役所を退職し、東京の会社へ転職となる都合上、本日より引越し等でバタバタしております、１０月２５日以降の日で再度調整して、ＬＧＷＡＮとクラウドが共存しやすい環境に再整理しようと思っております。
再度、ご相談しますので今しばらくお待ちください。
