### ISSUE TITLE
R05道路台帳補正業務　実施報告書　進捗確認について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#151]
お世話になります。
ご依頼のありました、実施報告書の１１月１日現在の進捗をまとめました。

"\\soja\総社市\更新データ\総社市道路台帳補正実施報告書R05Is編集.xlsx"

既設道路の延長については「作図済20231101可視基本情報」シートより確認をお願いします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
お世話になっております。確認しました。
ありがとうございます。
