### ISSUE TITLE
次回の資料受領及び打ち合わせ日程について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#152]
お世話になります。
先日、石井様よりご連絡いただきました日程につきまして

令和６年１月１０日　９時３０分から

上記で予定しております。
よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
株式会社アイ・サポート
橘田　様


いつもお世話になっております。
さて，標記の件につきまして総務課から連絡がありましたので，情報共有のため別添のとおり送付いたします。
よろしくお願いいたします。





＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

総社市役所　建設部　地域応援課　地籍管理係　石井
***@***.***
住所：総社市中央一丁目1番1号　　　〒719-1192
電話：0866-92-8293（地域応援係）
　　　0866-92-8286（地籍管理係）
FAX ：0866-92-8383

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

**Comment by isupport-kitta** [comment]
総社市地域応援課　石井様

あけましておめでとうございます。
本年もよろしくお願いいたします。

申し訳ありません。
上記コメントの件ですが、コメントにファイルを確認することができません。
お手数ですが、何かファイルを送付いただけるのであれば、下記の方法でお願いいたします。
・直接、私（kitta_m@isupport.co.jp）か長澤（nagasawa_j@isupport.co.jp）のメールに添付して送っていただく。
・こちらのコメントにアップロード（ドラッグ＆ドロップして）いただく。
・クラウド（\\soja\総社市）のいずれかのフォルダに置いていただいてパスをコメントで教えていただく。

いずれかの方法で総務課様の方からご連絡いただいた資料をお送りいただけますと幸いです。
よろしくお願いします。

**Comment by isupport-kitta** [comment]
総社市地域応援課 石井様

お世話になります。アイ・サポート橘田です。
先ほどはお電話ありがとうございます。
先日受領しました資料をスキャンしたPDFを以下の場所に保存いたしました。
ご確認をよろしくおねがいします。

\\soja\総社市\市役所⇔アイ・サポート\20240110受領資料\20240110農道用水路修正指示.pdf"
