### ISSUE TITLE
農道台帳の作成について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#157]
三宅様

お世話になっております。
昨日お電話でお話がありました、農道台帳作成の詳細をお伝えください。
「昨年度、１８０号関連で作図を行った農道に対して、農道調書、平面図、基図の作成」
と伺っております。

路線番号等が確定いたしましたらお伝えいただければと思います。
よろしくお願いします。

**Comment by isupport-kitta** [comment]
#120 こちらも確認していただけると幸いです。
よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅

お世話になっております。農道台帳整理についてです。
該当路線は以下のとおりです。

10-4003，4007，4008，4009，4010，4011，4012，4013，4014
10-4511，4512，4513

よろしくお願いいたします。

**Comment by isupport-kitta** [comment]
"\\soja\総社市\更新データ\農道調書作成用\10-4007"
上記の場所に10-4007路線の台帳を作成いたしました。
ご確認ください。問題がないようでしたら他路線も作成いたします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅

お世話になっております。10-4007路線確認しました。
上記の内容で了承が取れましたので、引き続き残りの路線の調書作成お願いいたします。

**Comment by isupport-kitta** [comment]
三宅様

ご確認ありがとうございます。
作業を進めさせていただきます。
