### ISSUE TITLE
農道台帳作成業務、完了のご報告

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#165]
お世話になっております。

ご指示のありました、農道路線
10-4003
10-4007
10-4008
10-4010
10-4011
10-4012
10-4013
10-4014
10-4511
10-4512
10-4513
の台帳を作成いたしました。

\\soja\総社市\更新データ\農道調書作成用\納品関連\20240329
上記箇所のフォルダに保存しております。
ご確認いただき、ご指摘、ご指示等よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅

お世話になっております。確認します。
修正等がありましたら連絡させていただきます。
よろしくお願いいたします。
