### ISSUE TITLE
報告書納品にお伺いする日程について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#166]
お世話になっております。
先ほどはお電話でのご連絡ありがとうございました。

3月27日水曜日　午前10：00～

上記日程でお伺いさせていただいてよろしいでしょうか。
よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅

お世話になっております。連絡遅くなってしまい申し訳ございません。
本日の10時からよろしくお願いします。

**Comment by isupport-kitta** [comment]
ありがとうございます。
