### ISSUE TITLE
道路台帳補正手順の流れ全般について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#17]
マニュアル　総社市道路台帳補正業務 仕様書 2022-09-26.docx　を更新しました。
まずは、これを確認ください。
![image](https://user-images.githubusercontent.com/86514652/192205989-d68c3759-8ee5-409b-a8d7-54f5ad7edd56.png)

**Comment by yamamoto-ryuzo** [comment]
一度、下記をマニュアルに基づいて質問してみてください。
質問する前に解ることもあるかもしれません。
必要に応じて、マニュアルの拡充をします。

告示（路線認定、廃止路線）
・道路網図の作成（必要に応じて採番し新規作成、認定年月日、廃止年月日入力）
・資料等図面があれば平面図作成（その際の取得年月日は認定年月日と同じ）
告示（道路拡幅）
・平面図作成
・道路網図は形状修正のみ（認定年月日はnullのまま）
供用開始（平面図作成）
・道路網図（認定年月日はnull）
・平面図作成（取得年月日はご指示ください。）

という認識でよろしいですか
また、内容欄記載の別途入力というのは何を指しておられますでしょうか。

**Comment by isupport-kitta** [comment]
ありがとうございます。
確認します。

**Comment by isupport-kitta** [comment]
各章ごとに弊社での作業内容をまとめました
・第3章　道路法第8条（第10条）の規定に基づく議案資料の作成	
	位置図作成のためQGISにて路線網図新規作成が必要
	議案第○○号　市道の路線認定について.xlsmを使用し議案第○○号　市道の路線認定について.pdfを作成
	
・第3章　道路法第9条の規定に基づく路線の告示資料の作成	
	何をすればよいのか不明です。
	
・第4章　道路台帳基本平面図作成	
	受領した資料及びデータ資料より道路平面図を作成
	
・第5章　道路法第18条の規定に基づく区域の告示資料の作成	
	「道路法18条の規定に基づく関係図面」を作成。（平面図作成が必須）
	R04-00-00区域変更・供用開始.xlsを用い告示資料の作成（道路法18条道路網図の作成が必要）
	
・第6章　道路法第18条の規定に基づく供用の告示資料の作成	
	「道路法18条の規定に基づく関係図面」を作成。（平面図作成が必須）
	R04-00-00区域変更・供用開始.xlsを用い告示資料の作成（道路法18条道路網図の作成が必要）

現在9月30日告示資料の第5章告示資料作成であっていますでしょうか
明日より道路法18条道路網図を新規作成したいと思います。

**Comment by isupport-kitta** [comment]
また、道路法第18条に規定に基づく区域の告示資料を作成する対象の路線は
路線認定とは関係なく、平面図作成依頼を受けていた路線でよろしいでしょうか
以下の路線になります。
![image](https://user-images.githubusercontent.com/110583661/192238578-d89cec55-954b-46ef-b915-6dc998de517d.png)

**Comment by isupport-kitta** [comment]
前述の2022/08/17受領分は12月告示分と記載がありましたので道路法18条管理網図の作成は現在行っておりません。

**Comment by yamamoto-ryuzo** [comment]
12月告示分は御社で都合の良いほうでOKです。
現段階で、日付をきちんと入力していれば整備は問題ないです。
雰囲気は、平面図と合わせて入力が入力漏れがないと思われます。

**Comment by isupport-kitta** [comment]
作業内容つづき
・第5章　道路法第18条の規定に基づく区域の告示資料の作成
　　◎道路法18条管理網図の作成、及び一覧作成（済）

**「道路法18条の規定に基づく関係図面」を作成。**（平面図作成済み）
**R04-00-00区域変更・供用開始　告示○○号.xlsを用い告示資料の作成**（道路法18条道路網図の作成が必要）

道路法18条（A3横）レイアウトを使用し、作成しようとしましたが、「市道編入等台帳」の［区域変更告示年月日］が未入力のためフィルタにかからず出てきません。当該属性の入力をお願いしたいのですが、よろしかったでしょうか、こちらで入力する箇所でしょうか

現在Excelで告示資料作成しております。
"\\soja\総社市\更新データ\議案用\R04\告示（路線認定・区域決定，変更・供用開始）　R04-08月\R04-10-31　区域決定・供用開始　告示〇〇号.xls"

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/21
のとおり入力お願いしたします。
マニュアル整備します。

**Comment by isupport-kitta** [comment]
"\\soja\総社市\更新データ\議案用\R04\告示（路線認定・区域決定，変更・供用開始）　R04-08月\R04-10-31　区域決定・供用開始　告示〇〇号.pdf"
を作成いたしました。

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/17#issuecomment-1257731527
について
道路法第18条に規定に基づく区域の告示資料を作成する対象の路線は
路線認定とは関係なく、平面図作成依頼を受けていた路線でよいです。

万が一、その中に、路線認定をしていない路線があれば協議をしてください。
路線認定が同時に必要な路線です。

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/30
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/29
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/28
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/27
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/26
分割しました。
回答済みも含めて、再度それぞれから回答します。
