### ISSUE TITLE
刑部三須線道路事業に伴う市道編入等について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#175]
総社市地域応援課　石井様

お世話になっております。
総社市/施設台帳/市道編入台帳/市道編入申請書/刑部三須線都市計画課に入っている刑部三須線
こちらの路線（10-3417）の平面図作成について、
当該道路を横断するように走っている3路線についての対応の仕方をお知らせください。

10-3358：終点変更かと思われます。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/8a37ca07-5c32-4f75-8c9a-ec9898b471a8)

10-3359：重複箇所の設定かと思われます。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/5288b068-1b3d-48ba-80a6-fea2aca2a56e)

13-5001：重複箇所の設定かと思われます。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/19f85820-fc85-408a-8445-9c75c5c2c491)

**Comment by isupport-kitta** [comment]
また、当該工事の断面図、構造物詳細図などありましたら、ご提示いただけますと助かります。
現状平面図に側溝の種別が記載されておりません。

また、「市道編入等台帳」レイヤにてポイントが設置されていません。
工事個所中心位置によろしくお願いします。
![image](https://github.com/city-soja-chiiki/douro_daityou_hosei/assets/110583661/d22cfdea-ad9f-4154-a1dd-9b754541ee01)

**Comment by city-soja-chiiki** [comment]
アイ・サポート　橘田　様

「当該工事の断面図、構造物詳細図など」とは，刑部三須線と10-3358・10-3359・13-5001との接点の工事部分のことでしょうか？
また「現状平面図」は刑部三須線のことでいいですか？
教えてください。

総社市地域応援課　石井

**Comment by isupport-kitta** [comment]
> アイ・サポート　橘田　様
> 
> 「当該工事の断面図、構造物詳細図など」とは，刑部三須線と10-3358・10-3359・13-5001との接点の工事部分のことでしょうか？ また「現状平面図」は刑部三須線のことでいいですか？ 教えてください。
> 
> 総社市地域応援課　石井

お世話になります。
「当該工事の断面図、構造物詳細図など」は当該工事全域のものの意味です。
現在いただいている平面図、交差点平面図では平面図に側溝種別等が記載されておらず不明です。
また曲線半径や縦断勾配も不明です。
「現状平面図」は現在いただいている平面図、交差点平面図を指しております。
また、このスレッド＃175での話題は全て「刑部三須線都市計画課」フォルダ内の道路のことになります。
よろしくお願いします。

**Comment by city-soja-chiiki** [comment]
アイ・サポート　橘田　様

10-3417を横断する3路線についてですが，お見込みのとおり10-3358は路線変更で議案のエクセルと図面が必要で，区域決定・供用開始の告示が必要です。10-3359・13-5001は重複個所の設定で区域変更・供用開始の告示が必要です。
また，市道編入台帳のレイヤのポイントを入れてみました。確認をお願いいたします。
あと，橘田さんのメールに10-3358の議案の参考図面を送付しますので，確認をお願いいたします。

総社市地域応援課　石井

**Comment by city-soja-chiiki** [comment]
アイ・サポート　橘田　様

都市計画課から追加の図面をもらいました。
総社市/施設台帳/市道編入台帳/市道編入申請書/刑部三須線（10-3417）都市計画課にR6.5.1追加資料を入れましたので，確認をお願いいたします。

総社市地域応援課　石井

**Comment by isupport-kitta** [comment]
> アイ・サポート　橘田　様
> 
> 10-3417を横断する3路線についてですが，お見込みのとおり10-3358は路線変更で議案のエクセルと図面が必要で，区域決定・供用開始の告示が必要です。10-3359・13-5001は重複個所の設定で区域変更・供用開始の告示が必要です。 また，市道編入台帳のレイヤのポイントを入れてみました。確認をお願いいたします。 あと，橘田さんのメールに10-3358の議案の参考図面を送付しますので，確認をお願いいたします。
> 
> 総社市地域応援課　石井

お世話になります。アイ・サポートの橘田です。
10-3358の路線変更の位置図及び議案のExcelの追加をいたしました。
\\soja\総社市\更新データ\議案用\R06\6月議会\議案（路線認定）　R06-05月
上記箇所に置いております。ご確認をよろしくお願いします。
