### ISSUE TITLE
道路台帳平面図管理システム（管理者用）.qgs　の更新情報

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#20]
レイヤ　道路基本情報　の属性を　縦長で見にくかったので、コンテナ化して2列表示にしました。
![image](https://user-images.githubusercontent.com/86514652/192408564-2835ee7a-8ff2-4e09-ac6e-6f730aaaf22f.png)

**Comment by yamamoto-ryuzo** [comment]
路線検索を追加しました。
![image](https://user-images.githubusercontent.com/86514652/192433842-56f6c5a0-c047-4f21-abe0-d1b0a7b0566c.png)

**Comment by yamamoto-ryuzo** [comment]
印刷レイアウトを追加しました。
![image](https://user-images.githubusercontent.com/86514652/192691793-65c76475-3649-464f-826d-2366d2e6d3f5.png)

**Comment by isupport-kitta** [comment]
印刷レイアウトを使用してPDFを作成したときに
道路管理網図の表示が青の破線で表示されてしまうのはどこを編集したら直りますか？

**Comment by yamamoto-ryuzo** [comment]
それは未供用になっているからです。

**Comment by isupport-kitta** [comment]
供用に修正してpdf出しなおします。
ありがとうございます。

**Comment by yamamoto-ryuzo** [comment]
図郭検索を追加しました。
![image](https://user-images.githubusercontent.com/86514652/192928321-3ba35b29-3c4c-46ec-ad3e-49876cefd05a.png)

**Comment by isupport-kitta** [comment]
検索機能追加ありがとうございます。

こちらに報告があった事を記載させていただきます。
・「地籍」レイヤの注記が表示されない。
・「道路台帳平面素図」レイヤの表記にマーカーラインが含まれている。

**Comment by yamamoto-ryuzo** [comment]
すいません・・・画像付きでお願いします。
文書だけで行くと。
・「地籍」レイヤの注記が表示されない。
　注記はもともと使っていないのですが？
・「道路台帳平面素図」レイヤの表記にマーカーラインが含まれている。
　どのレイヤ化わかりません。
　境界点がはっきりしないといけないものはマーカーラインです。

**Comment by yamamoto-ryuzo** [comment]
とりあえず
・「道路台帳平面素図」レイヤの表記にマーカーラインが含まれている。
は点になっていたので，修正しておきました。
![image](https://user-images.githubusercontent.com/86514652/193709532-1bda0fcc-1803-4dc6-9ab4-77cd0be224b4.png)

**Comment by yamamoto-ryuzo** [comment]
・「地籍」レイヤの注記が表示されない。
ラベル表示ですね・・・
修正しておきました。
現在，LGWANはレイヤ選択で自由に表示を選択できる仕様に変更しているので，こちらも近日中にそうします。

**Comment by isupport-kitta** [comment]
画像付きにするように気を付けます。
即時の対応ありがとうございます。

**Comment by yamamoto-ryuzo** [comment]
路線認定のレイアウトフィルタを厳格化しました。
合わせて、路線廃止の場合の表示項目を変更しました。
これにより、路線認定-2500固定　において、取得日と認定日等が異なるときに非表示となります。
取得年月日が9/30のままのため、路線認定に表示されません。
１件は修正しました。9/30のままの属性は修正ください。
![image](https://user-images.githubusercontent.com/86514652/196702293-6a4526fe-7337-41f9-a546-cb09b16a4028.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。
取得日が「2022/09/30」になっていた認定路線を「2022/10/31」に修正しました。

**Comment by isupport-kitta** [comment]
消去日を過ぎた側溝の表示が非表示とならず、赤の破線になっています。
下図のdayは2022/12/28です。　側溝の消去日は2022/10/31です。
![image](https://user-images.githubusercontent.com/110583661/196829346-f0ac67ba-5acc-42e2-9846-bebe2e706107.png)

**Comment by isupport-kitta** [comment]
現在、歩道のラインも道路部境界を作図しております。
道路部境界のフィールド属性に歩道を追加するか別レイヤにして現在の道路部境界からコピーするかですが、
数が増えてきたので何かしらの印をいれておきたいところです。
ご一考よろしくお願いします。
![image](https://user-images.githubusercontent.com/110583661/196829723-58bb6e11-991e-4ac8-887e-3160fa2cc4c5.png)

**Comment by yamamoto-ryuzo** [comment]
> 消去日を過ぎた側溝の表示が非表示とならず、赤の破線になっています。 下図のdayは2022/12/28です。　側溝の消去日は2022/10/31です。
　「廃止済」を追加、標準で非表示にしました。

![image](https://user-images.githubusercontent.com/86514652/196841166-b3c559d3-00c2-4e39-97d1-4287deddada8.png)

**Comment by yamamoto-ryuzo** [comment]
> 現在、歩道のラインも道路部境界を作図しております。
> 道路部境界のフィールド属性に歩道を追加するか別レイヤにして現在の道路部境界からコピーするかですが、
> 数が増えてきたので何かしらの印をいれておきたいところです。
> ご一考よろしくお願いします。

なんとなく、レイヤが増えて作図の手間が増えるのと、管理上の必要性小さいことから同一レイヤにしました。
マニュアルも更新しました。
現在の作業でOKです。
分離帯がないとこがあるようです。確認ください。
![image](https://user-images.githubusercontent.com/86514652/197098631-719601a3-8206-40e1-9d55-96ead6756316.png)

**Comment by yamamoto-ryuzo** [comment]
路線検索の表示項目に「変更年月日」を追加しました。
![image](https://user-images.githubusercontent.com/86514652/197110993-37ec1f33-7797-4616-ba2c-ca1a7ddbcf9c.png)

**Comment by yamamoto-ryuzo** [comment]
レイアウト　路線認定　のスケールを自動計算するように修正しました。
念のため2500固定は当面残します。
![image](https://user-images.githubusercontent.com/86514652/197454892-21a1da37-55aa-4c58-8d21-91ddc20b4514.png)

**Comment by isupport-kitta** [comment]
レイアウトの変更ありがとうございます。
変更路線が2重に地図帳出てきてしまう（変更年月日が新旧両方入っているため？）ので一度PDFにした後に不要なページを削除しようと思います。

**Comment by yamamoto-ryuzo** [comment]
> レイアウトの変更ありがとうございます。 変更路線が2重に地図帳出てきてしまう（変更年月日が新旧両方入っているため？）ので一度PDFにした後に不要なページを削除しようと思います。

自動判定するように修正しました。
変更路線は，消去されていないほうが「変更後」のはずなので，下記のとおり修正しました。
![image](https://user-images.githubusercontent.com/86514652/197466890-fd47818e-6f3f-483e-a38e-9605aebc1954.png)

**Comment by isupport-kitta** [comment]
自動判定の設定ありがとうございます。
PDFを出してみます。

**Comment by isupport-kitta** [comment]
\\soja\総社市\更新データ\議案用\R04\12月議会\議案（路線認定）\路線認定(A4縦).pdf
に新しいレイアウトで総社・一宮BP関連の路線認定を出しました。
5ページ目、6ページ目が変更前の路線が見切れてしまいます。
変更前の路線は図面からはみ出していてもよろしいですか。
![image](https://user-images.githubusercontent.com/110583661/197482658-46870f03-a9e2-41f1-9e99-da4e6235c2a9.png)
![image](https://user-images.githubusercontent.com/110583661/197482716-97726e39-6afc-4b6b-b881-63dd8310ebf5.png)

**Comment by yamamoto-ryuzo** [comment]
今後は，レイアウト　路線認定（A4縦）を利用ください。
そのうち，2500固定は削除予定です。

**Comment by yamamoto-ryuzo** [comment]
あ～～了解です！
廃止路線の方が異常に長いからですね・・・
通常はこのような変更はあり得ないのですが・・・
ちょっと考えてみます。
