### ISSUE TITLE
市道編入等台帳管理システム（管理者用）.qgs　の更新情報

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#21]
レイヤ　道路法18条管理網図　のコンテナを見直し、2列+タブ分けを行いました。
作業の上で並びを修正したほうが良ければ連絡ください。
そちらで修正していただいてもOKです。
![image](https://user-images.githubusercontent.com/86514652/192412238-b8aa1b7c-812d-4664-936e-54accaa00d13.png)

**Comment by yamamoto-ryuzo** [comment]
年度を自由に追加できるようになりました。
コード表‗年度　に追加してください。
![image](https://user-images.githubusercontent.com/86514652/192413284-16817cd5-6fa5-43b0-b217-589245275bfc.png)

**Comment by yamamoto-ryuzo** [comment]
路線認定（路線網図）_路線名称が編集不可となっていたのを修正しました。
![image](https://user-images.githubusercontent.com/86514652/192414139-43d70030-6e10-48c3-99ef-7b3174abae25.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。確認いたします。

**Comment by yamamoto-ryuzo** [comment]
受託業者が入力したほうがスムースなものと市の入力を分離しました。
（業者）のタブは、受託業者で入力お願いします。
区域変更は路線認定に伴う、区域決定を除いた路線です。
最終の告示の本数はこの路線+区域変更＝（通常）供用開始となるはずです。
![image](https://user-images.githubusercontent.com/86514652/192453744-a82c7997-91b8-428d-b373-b31e0782a6d4.png)

**Comment by isupport-kitta** [comment]
拝見しました。
市道編入等台帳-地物属性について
（業者）タブが3つありますが、今回の区域決定、供用開始は後ろ2つのタブの［区域変更（決定・廃止）告示年月日］と［供用開始告示年月日］を2022/10/31にしたらよろしいでしょうか

**Comment by yamamoto-ryuzo** [comment]
OKです。
路線認定もお忘れなく入力ください。
路線+区域変更＝（通常）供用開始　
2022/10/31　でフィルターをかけて、路線+区域変更＝（通常）供用開始　となれば、まずは一安心です。

**Comment by isupport-kitta** [comment]
廃止路線の場合はどうなりますか
真ん中の区域変更（決定・廃止）のタブのみでよろしいですか

**Comment by isupport-kitta** [comment]
道路区域（業者）タブの区域変更は通常新設道路の路線番号でよろしいですか
市道拡幅の路線番号を入れるのですか

**Comment by isupport-kitta** [comment]
市道拡幅の台帳の場合は道路区域（業者）や供用開始（業者）に2021/04/08と入力されておりますが、これらも変更して2022/10/31にしてよろしいですか

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/21#issuecomment-1259094979
こうしたほうがよかったですね。
これで、路線+区域変更＝（通常）供用開始が合うと思います。
なので、路線認定も入れてください。
![image](https://user-images.githubusercontent.com/86514652/192465094-1be0ec0d-c7da-4f4a-8fcc-2814f91c13fa.png)

**Comment by yamamoto-ryuzo** [comment]
「道路区域（業者）タブの区域変更は通常新設道路の路線番号でよろしいですか
市道拡幅の路線番号を入れるのですか」
の件ですが、確かに紛らわしいですね・・・
多分、全部入れたほうがわかりやすいみたいです。
路線+区域変更＝（通常）供用開始　ではなく、それぞれの本数が、それぞれの書類の本数にあっていれば問題ないです。
この項目は単純に入力ミスのための項目なので、ご希望があれば変更します。
ご希望があれば、別のISSUESを立ち上げてください。

**Comment by yamamoto-ryuzo** [comment]
路線検索を追加しました。
![image](https://user-images.githubusercontent.com/86514652/192470951-ddffdaf9-f344-4c88-94ac-b93d25f1d7fa.png)

**Comment by yamamoto-ryuzo** [comment]
市道編入の検索を追加しました。
![image](https://user-images.githubusercontent.com/86514652/192534129-69c3a251-d15e-4f3a-8be0-564e920f9be4.png)

**Comment by yamamoto-ryuzo** [comment]
属性に告示附図‗年度と追加しました。
これにより、附図番号を市道編入申請年度から告示年度に対応するために追加しました。
![image](https://user-images.githubusercontent.com/86514652/192689105-cf48902a-9581-455e-92a5-9fd3d9b90e6e.png)

**Comment by yamamoto-ryuzo** [comment]
ファイルを開く機能の復活
市道編入台帳からファイルを開くを選択すると、それぞれの市道編入フォルダが開きます。
![image](https://user-images.githubusercontent.com/86514652/193590332-1f5767e9-04d5-4d56-bb79-e19e84024734.png)
