### ISSUE TITLE
ラベル表示について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#32]
現在，各作業に必要と思われるラベルを表示しているつもりですが，追加で必要な属性のラベル表示があればこちらにお願いします。
最低限，下記情報をお願いします。
[レイヤ名]　　ラベルを追加したいレイヤ
[スタイル]　　レイヤで使用しているスタイル　「編集，表示とかのスタイル名」
[属性]　　　　ラベル表示したい属性名
以上。

**Comment by isupport-kitta** [comment]
ありがとうございます。

**Comment by yamamoto-ryuzo** [comment]
地籍のラベルを選択できるようになりました。
「地籍情報表示」をチャックしたのちに，再描画すればOKです。
どうような，表示方法がよいものがあればISSUESをあげてください。
![image](https://user-images.githubusercontent.com/86514652/197942210-35aecb8d-f580-4f88-860d-1286adfa09ed.png)
