### ISSUE TITLE
今後のスケジュールについて

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#33]
お世話になります。
今後のスケジュールの確認及び確認事項をまとめました。
![image](https://user-images.githubusercontent.com/110583661/194505286-8b401202-87f4-4250-83f8-5944f2316b99.png)
10月以降のライン及びマークは予定で入れております。

確認事項1：既設道路作成についてR03業務：50km、R04業務：100kmを目安に作業を進めてよろしいでしょうか。

確認事項2：第3章（8条）の告示資料作成のタイミングを教えてください。

確認事項3：次回の第4章から第6章（18条）の告示資料のタイミングは12月中旬でよろしいでしょうか。

よろしくお願いします。

**Comment by yamamoto-ryuzo** [comment]
確認事項1：既設道路作成についてR03業務：50km、R04業務：100kmを目安に作業を進めてよろしいでしょうか。
R03の報告書は下記に入れておきます。
\\soja\総社市\市役所⇔アイ・サポート
概算で140ｋｍです。
下記にて報告ください。
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/7

**Comment by yamamoto-ryuzo** [comment]
確認事項2：第3章（8条）の告示資料作成のタイミングを教えてください。
2章にあったものを3章に移動し、内容を充実しました。
そろそろ担当者から連絡あると思います。
![image](https://user-images.githubusercontent.com/86514652/195249503-60a6bb1c-8a56-4d43-948c-14e729374b6a.png)
