### ISSUE TITLE
現地調査について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#34]
現地調査に行こうと思います。

確認事項１：現地調査の対象は新設道路工事、道路拡幅工事でよろしいでしょうか

確認事項２：図の赤枠で囲った新たに整備した道路部幅員を計測することでよろしいでしょうか

確認事項３：計測の仕方はメジャー等で概ね近いことを確認することでよろしいでしょうか

![image](https://user-images.githubusercontent.com/110583661/195472718-423b19b2-7a66-4329-b14a-8ec959926da8.png)

**Comment by yamamoto-ryuzo** [comment]
確認事項１：現地調査の対象は新設道路工事、道路拡幅工事でよろしいでしょうか
　補正をした箇所すべてとなります。

確認事項２：図の赤枠で囲った新たに整備した道路部幅員を計測することでよろしいでしょうか
　延長を含めて、台帳に記載されたすべての数値となります。

確認事項３：計測の仕方はメジャー等で概ね近いことを確認することでよろしいでしょうか
　精度は、少なくとも現在は10㎝単位で表現しているのですが、基本は1㎝単位です。
　公共測量ではなく、現地確認のための測量となります。

　測定方法は、現在は様々な機器があるので、お任せしますが、最近はドローンが多いです。

　今回は、測定横断は必ず資料を残してください。
　ドローン以外の場合は、測定部の写真を整理して横断個所として整理したいです。

　現地に、行きだすと今までGISの入力だけでは見えてこなかったものが見えてきますが、現場危険なので、くれぐれも無理のないようにお願いします。

　件数は極めて少ないはずですが、作図の関係でどうしても作図寸法と現地実寸が合わない箇所が発生すると思います。
　その場合は、別途実測寸法属性をと考えております。
　連絡お願いします。

　その他の測定方法でもOKですので、最終的な測定方法が決まったら教えて下さい。

**Comment by city-soja-chiiki** [comment]
追伸・・・
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/7#issuecomment-1276995194
を参照ください。

**Comment by yamamoto-ryuzo** [comment]
ドローン以外の簡易な測定で精度の高い安価なおすすめ品。
測定イメージは
https://www.youtube.com/watch?v=-f36jnLhYsw
の3分あたりです。
機器はこちら
https://www.bosch-professional.jp/jp/ja/products/glm-150-27-c-0601072Z50
一度ご検討ください。

**Comment by yamamoto-ryuzo** [comment]
（点間距離の測定）
利用者の評価だと、結局屋外は無理って感じの投稿が多いようです。
この機種については、点間距離は？なようです。
計れる機器も、遠くのものは精度がやはり無理とか・・・
ひょっとしたら、現在計画されているIPADで測定断面近くまで行って、計るのが一番精度が高いかもです。
IPADの屋外測定結果、また、見せてください。
（延長）
転がすデジタルメジャーのチェックでOKです。

**Comment by isupport-kitta** [comment]
お世話になります。
先日現地調査に行った時の写真をアップロードしました。

\\soja\総社市\更新データ\現地調査\20221018

延長が長いと精度がいまいちかもしれません。
その時はメジャーで測って写真内の数字を書き換える感じでいこうと思います。

**Comment by yamamoto-ryuzo** [comment]
結局、アナログがまだまだ強いということですね・・・
延長はデジタルメジャー、幅員はメジャーでお願いします。
撮影時には、延長、幅員共にメジャー本体の撮影は不要です。
安全に撮影、寸法確認をお願いします。

**Comment by yamamoto-ryuzo** [comment]
幅員は、写真のようにIPADで採寸できる方向がベストですが、下記写真のような誤差はNGです。
撮影方法が固まったら、併せてマニュアル整備を行います。
![image](https://user-images.githubusercontent.com/86514652/197456773-b6dc49da-2b5a-43c8-8821-3c5c060c00ed.png)

**Comment by yamamoto-ryuzo** [comment]
とりあえず基本的なことろのみマニュアル追加しました。
![image](https://user-images.githubusercontent.com/86514652/197467781-3db8e2da-589f-43d8-8759-aab0224aa8da.png)

**Comment by yamamoto-ryuzo** [comment]
精度管理について。
現地確認の採寸は1㎝単位でお願いしておりますが。
その写真への表記は10㎝単位でもOKです。
アプリの表記精度を変えることで手間が省けるのなら，省力化の方向でお願いします。
ただし，4ｍと3.9ｍでは，いろいろ違うので気を付けてください。

**Comment by isupport-kitta** [comment]
ありがとうございます。
以後、ご指示のようにいたします。
