### ISSUE TITLE
テスト1

### ISSUE THREAD

**Issue by isupport-shimoda** [city-soja-chiiki/douro_daityou_hosei#4]
テスト1

**Comment by isupport-shimoda** [comment]
テスト2

**Comment by isupport-shimoda** [comment]
テスト3

**Comment by isupport-kitta** [comment]
test1

**Comment by isupport-kitta** [comment]
> テスト3

テスト３へ返信

**Comment by yamamoto-ryuzo** [comment]
右上のwatchを登録すると、設定によりメールが届くようになります。
![image](https://user-images.githubusercontent.com/86514652/189917538-6cb7b541-2c9b-4d6e-9658-59784c669b1b.png)

**Comment by yamamoto-ryuzo** [comment]
前に同じISSUESがあればそのアドレスをコピーしたら、リンクが取れます。
例えば、↓な感じです！
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/3

**Comment by isupport-kitta** [comment]
> 前に同じISSUESがあればそのアドレスを一方にコピーしたら、自動で相互リンクが取れます。 例えば、↓な感じです！ #3

なんとなくわかってきました。
ありがとうございます。
メールで問い合わせるよりもこちらの方が早くて良いと思います。

**Comment by isupport-shimoda** [comment]
情報ありがとうございます、watch登録、相互リンク承知しました。
#3

**Comment by city-soja-chiiki** [comment]
解決したら、クローズする癖にしとくと、残った課題だけが、ISSUESに残ってわかりやすいです。

**Comment by isupport-shimoda** [comment]
クローズ承知しました。
