### ISSUE TITLE
路線網図作図の確認

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#40]
下記箇所ですが，路線網図を書き換えているように思えますが，複写してから編集しました？
![image](https://user-images.githubusercontent.com/86514652/198006809-8c79b824-dddd-42e5-98b0-c34f8730534c.png)

**Comment by isupport-kitta** [comment]
すいません。私の認識が間違っていました。
路線網図も消去して、新規作成なのですね。
明日戻しておきます。

**Comment by yamamoto-ryuzo** [comment]
違います。
![image](https://user-images.githubusercontent.com/86514652/198211511-0618bb3d-d3ca-44d6-ae30-e424b59d4222.png)
です。
基本，入力ミス以外で，確定したデータとして消すことはあり得ません。
消したというデータを入力です。
これにより非表示となります。
時系列を持つデータ編集の基本と思ってください。
