### ISSUE TITLE
道路局長通達：路線認定、区域決定及び供用開始等の取扱について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#41]
見解がいろいろあるので，通達を基準にマニュアルの整備を行っていきます。
必ずご一読ください。
![image](https://user-images.githubusercontent.com/86514652/198028753-edc1c570-55df-4097-b27d-64a4a28b5bc1.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。
読んでみます。
