### ISSUE TITLE
データベースの統合について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#47]
データベースの構成をインターネット，クラウド，LGWANで統合し，それぞれのデータやり取りを簡素化したいと考えております
。
つきましては，11/12-13日に実施予定ですが，作業よろしいでしょうか。

**Comment by isupport-kitta** [comment]
ありがとうございます。
よろしくお願いします。

**Comment by yamamoto-ryuzo** [comment]
本日の作業は終了しました。
異常があったらすぐに連絡ください。

今後は。
　1.クラウドデータ（道路台帳）を　インターネットに反映
　2.LGWAN内で利用するクラウドデータ（道路台帳）を　クラウド構成に変更　
　3.クラウド内で利用するLGWANデータ（地籍データ等）を　LGWAN構成に変更

データ移行の業務も御社かWILLWAVE社にお願い予定です。
これにより，道路台帳のデータをインターネット，クラウド，LGWAN　で利用可能となります。
併せて，クラウド⇔ＬＧＷＡＮで相互バックアップ体制が完成します。

となります。
その後，定期的なデータ移行業務を　できればお願いしたいと思っています。

**Comment by nagasawajun** [comment]
統合作業ありがとうございました。
データ移行について、弊社でもできそうな内容でしたら、是非対応させていただきたいと思います。
どうぞよろしくお願いいたします。
