### ISSUE TITLE
第10章　総社市道路台帳補正標準歩掛　の追加

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#48]
報告書を定例市議会毎に受け取っていただくこととなったので，その歩掛を作成しました。
![image](https://user-images.githubusercontent.com/86514652/201343088-80c534b8-1d4d-48f2-b37f-524497ce3c7d.png)

**Comment by yamamoto-ryuzo** [comment]
仕様変更による修正業務
![image](https://user-images.githubusercontent.com/86514652/201344445-c19e2ed3-8176-49d9-8276-b548dae85309.png)

**Comment by yamamoto-ryuzo** [comment]
道路法18条管理網図作成
![image](https://user-images.githubusercontent.com/86514652/201346015-53b22616-1dfa-4450-901c-97b36e0270df.png)

**Comment by yamamoto-ryuzo** [comment]
歩掛エクセルシートの修正
C:\総社市\市役所⇔アイ・サポート\報告書（仮）
総社市道路台帳補正実施報告書（入札業者）.xlsx
を参照ください。
![image](https://user-images.githubusercontent.com/86514652/201348365-3c5b889f-11fb-4edf-9fdd-60d529ea1bb0.png)

**Comment by yamamoto-ryuzo** [comment]
最近，三宅さんに任せっぱなしで概ねしか把握しておりませんが，歩掛にない作業が発生している場合は，教えて下さい。

**Comment by yamamoto-ryuzo** [comment]
認定外を作業していただけるようになったので，追加しました。
![image](https://user-images.githubusercontent.com/86514652/202595207-341de678-b33f-4da2-ad7a-e77d0005eb1f.png)

**Comment by yamamoto-ryuzo** [comment]
修正に関する回数について追加しました。
![image](https://user-images.githubusercontent.com/86514652/202605530-0508325c-250c-433c-88c0-3892d9a9bf6b.png)

**Comment by nagasawajun** [comment]
歩掛の追加ありがとうございます。
