### ISSUE TITLE
道路基本情報レイヤーの地物が表示されない

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#5]
現在、道路台帳平面図システム（作業用）.qgsで道路基本情報レイヤの地物が表示されない状態になっています。
レイヤパネルのチェックをしていても、地物、注記ともに表示されません。
設定などに問題があるのか、どこを見ればよいのか教えてください。
![image](https://user-images.githubusercontent.com/110583661/190029672-7a6c1274-8a47-48e8-ac02-89057526aefd.png)
（見やすくするため区割線はグレーから紫に変更しています。）

**Comment by city-soja-chiiki** [comment]
基本的に、複数のプロジェクトファイルで作業するのではなく、システムから立ち上がった、画面にあるプロイジェクトを「テンプレートファイル」を正として作業が一番エラーが少ないです。
　なので、管理者以外のファイルはないのがベストなので、スタイルだけを修正しているようなので、スタイルにIS01とか、自分の名前を付けるとかして・・・（管理者）に保存してもらった方がいいと思います。

　最終的には（管理者）は削除したいです。

　非表示の件は、追加の際に座標系の設定がCRSを2447に再設定が抜けていました。
　・・・（管理用）2447に再設定しておきました。
　設定方法は、下記のような感じです。

![image](https://user-images.githubusercontent.com/110579656/190068689-83480f10-1132-4f73-a649-bd17476a3223.png)

**Comment by city-soja-chiiki** [comment]
ところで、タイトルは問題の具体的な項目を書いたほう後でわかりやすいです。

**Comment by isupport-kitta** [comment]
ありがとうございます。CRSを2447に設定することで解決しました。
以後プロジェクトファイルは道路台帳平面図管理システム（作業用）.qgsを使用し
他作業用は削除いたします。
作業員各人でスタイルを変更した場合はスタイルファイルを保存しておいて作業ごとにスタイル設定をしてもらうようにします。

**Comment by city-soja-chiiki** [comment]
今後の更新を考えると、
1.スタイルは、プロジェクトファイルに作業員各人の記号を決めて「IS01、IS02」とかで登録
2.テーマを作業員各人で登録　自分の好きな表示状態を登録できます。
![image](https://user-images.githubusercontent.com/110579656/190532790-52e17596-974a-4b4b-9559-182d45a6e652.png)
がよいと思います。

問題点は、スタイルはバージョンアップの都度、エラーの原因となりやすいです。
共通用スタイルを使って問題なのなら、相談して共通のスタイルを使ったほうがいいのはいいです。

**Comment by city-soja-chiiki** [comment]
ゴールは
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/12
です。
