### ISSUE TITLE
既設道路ベクトル作成時、頂点編集が出来ない現象について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#53]
既設道路の作成を行っている際に
「道路基本情報」レイヤの地物の追加をしている時に
頂点編集ができないオブジェクトが出来てしまいました。
再度追加したり、移動したりしたのですが、どうやっても頂点編集ができません。
地物の頂点の中に「nan nan」という箇所があるところまではわかったのですが、どうすれば修正できるのかわかりません。
修正方法がありましたらご教授お願します。

![image](https://user-images.githubusercontent.com/110583661/203665505-aa6c410f-177d-4b89-9c16-b9e259ede6b6.png)

**Comment by yamamoto-ryuzo** [comment]
原因は不明ですが，数値でないデータ「nan」が入っています。
たぶん，簡単なのは一度削除です。
属性はOKなようなので，部分削除がいいと思います。
そして再度部分追加です。
これも出来ないようならまた投稿ください。直接見てみます。
![image](https://user-images.githubusercontent.com/86514652/203669785-90e572a9-bf90-47b2-8649-4cef51b8383d.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。部分の削除をしてみましたが、地物を選択することができず削除できません。
お忙しいところ申し訳ありません一度確認をお願いします。
路線番号2038　図郭番号D4-52　区間番号2000
よろしくお願いします。
![image](https://user-images.githubusercontent.com/110583661/203876684-0a9f862c-5a34-4a11-bd1a-8e16a921882b.png)

**Comment by yamamoto-ryuzo** [comment]
とりあえず，地物だけをコピーしてジオメトリ修復したらなくなりました。
原因は不明ですがやはりエラーだったようです。
復旧しておきました。
![image](https://user-images.githubusercontent.com/86514652/203991029-0e90be22-9c9e-4cf0-b557-50956888456e.png)

**Comment by isupport-kitta** [comment]
再度、同じ症状が発生しました。
お忙しいところ申し訳ありません一度確認をお願いします。
路線番号10-3587　図郭番号E5-25　区間番号0300及び0400

なぜこの症状が発生するのか不明です。
また、再度起こった時の対処の方法を教えていただけましたら助かります。
よろしくお願いします。

**Comment by yamamoto-ryuzo** [comment]
結果だけ言うと，下記2点の点？になっているようです。
ジオメトリも実は，点・線・面を同一ジオメトリで保存できる仕様もあるので，意図せず，そちらになっているのだと思います。
雰囲気，ダブルクリック？あたりで，点のような線を描いたとか？
とりあえず，この点を部分削除です。
後学のため，まずは，それを試してみてください。
![image](https://user-images.githubusercontent.com/86514652/204462232-9cc771bf-b5fa-403d-9f0c-d6bc3719753b.png)
![image](https://user-images.githubusercontent.com/86514652/204462279-2f7fc5ee-1c70-4b23-b233-2ce2621ede33.png)


![image](https://user-images.githubusercontent.com/86514652/204461752-ce4b40c9-3c32-44a1-b99f-0a6bcc678563.png)

**Comment by yamamoto-ryuzo** [comment]
どうも無理っぽいです。
対応法
1.壊れたジオメトリをエクセルにコピー
2.「nan」を削除
　LINEなので，2点以上になるようにお願いします。
3.　表計算レイヤの追加
![image](https://user-images.githubusercontent.com/86514652/204474113-51ee27cd-c534-4178-a9d8-f2fa679e1bdd.png)
4.読込方法は下記の感じ
　地物を選択，エンコード　WTK，空間座座標系　2447
　で読み込む
![image](https://user-images.githubusercontent.com/86514652/204474783-451b4dca-253d-495f-aa10-d9caa45d37c6.png)
5.地物のコピーで　「道路基本情報」へ
6.エラーの地物は削除

　「表計算レイヤの追加」は一度覚えると何かと便利です。
　適当な座標からジオメトリを生成して，やることもただのエクセル関数で簡単に可能です。

**Comment by yamamoto-ryuzo** [comment]
タイプは「マルチライン」を選択してください。
指定し忘れてました。
![image](https://user-images.githubusercontent.com/86514652/204476323-3e8ec112-bebc-4c2b-8510-2ccd70f1c302.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。
次回、エラーが出た時に教えていただいた方法で修復を試みてみます。
また、分からないことがありましたら教えてください。
