### ISSUE TITLE
QGIS 3.22.13へバージョンアップ+プラグインの見直し

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#57]
QGIS 3.22.13へバージョンアップ　しました。
このシステム専用のプラグインとして追加しているものは，現在，コアプラグインとしてQGIS本体に追加していましたが，通常のプラグインとしての配信が可能となったので，順次，見直してゆきます。
プラグインの動作がおかしかったらこちらへ！

プラグインの見直しが終了後クローズします。

**Comment by isupport-kitta** [comment]
昨日一日作業をしてみました。
特に問題なく使用できているようです。
ありがとうございます。
