### ISSUE TITLE
R4.12.28 区域変更・供用開始図面　修正依頼について

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#58]
地域応援課　三宅
区域変更のエクセルシートの修正依頼です。

10-3098　井手支線3098号道　区間　総社市　井手303番3地先　～　総社市　井手211番3地先

13-5024　上林支線5024号道　区間　総社市　上林57番10地先　～　総社市　上林63番5地先

12-3228　真壁支線3228号道　区間　総社市　真壁193番6地先　～　総社市　真壁191番5地先

1021　     北宮福井本線            区間　総社市　福井97番6地先 　 ～　総社市　福井98番1地先

![R4 12 28 区域変更1](https://user-images.githubusercontent.com/110579656/206636729-98fffc7c-9298-4fa6-8225-fed3ac0aa3fe.png)

1037　　　滝の端草田本線　変更後の幅員　最小　5.3ｍ　最大　区域を広げた最大幅員　　　延長　512.6ｍ

16-5065　　福谷支線5065号道　区間　総社市　福谷1574番1地先　～　総社市　福谷1574番1地先
　　　　　   延長　変更前　28.5ｍ　変更後　16.8ｍ

16-3019　　福谷支線3019号道　区間　総社市　福谷1572番1地先　～　総社市　福谷1577番1地先
　　　　　　変更前の最大幅員確認すること

16-5079　　福谷支線5079号道　変更前の最大幅員確認すること　延長も確認

16-5069　　福谷支線5069号道　区域　総社市　福谷1352番1地先　～　総社市福谷1352番1地先
　　　　　　変更前の最大幅員確認すること

16-5009　　福谷支線5009号道　区域　総社市　福谷1354番1地先　～　総社市　福谷1356番5地先　

![R4 12 28 区域変更2](https://user-images.githubusercontent.com/110579656/206638371-25bfc886-9cbf-4b62-b952-926686e25104.png)

**Comment by isupport-kitta** [comment]
三宅様
ご連絡ありがとうございます。
道路法18条管理網図及びExcelの修正が完了したのでお知らせいたします。
合わせて、道路法18条(A3横)1_500_R04-12-28.pdfの11～13Pも修正いたしました。
ご確認をよろしくお願いします。

\\soja\総社市\更新データ\議案用\R04\12月議会\告示（区域決定，変更・供用開始）R04-12月

**Comment by isupport-kitta** [comment]
> 幅員は敷地の幅員！ つまり，車道幅員ではなく，区域＝敷地の幅員ですので，よろしくお願いいたします。

ありがとうございます。
18条管理網図作成時に気をつけます。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
お世話になっております、R4.12.28供用開始図面の修正です。

[【修正】　R4.12.28供用開始図面.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10263609/R4.12.28.pdf)

よろしくお願いいたします。
