### ISSUE TITLE
既設道路の道路線作図時「R=○○」と指定がある箇所について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#59]
お世話になります。
先ほど三宅様より下図の箇所の道路線についてRの指定があるがポイントで置かれている点についてご指摘をいただきました。（下の図はカーブで整備し直しております）
![image](https://user-images.githubusercontent.com/110583661/206660050-6fed7f14-538a-456a-b9df-68e00cdada3a.png)

現在までは「半径指定による円形ストリングの追加」を使用しておらず、市道台帳ラスターに合わせてポイントで整備しておりました。
下図のようにカーブで作図するとラスターに合わない箇所が出てくるかと思われますが、カーブで引いた方がよろしいでしょうか（茶色がカーブ作図）
![image](https://user-images.githubusercontent.com/110583661/206660876-b08f36e9-b637-45bf-a1c4-66d63a2e19ab.png)

**Comment by yamamoto-ryuzo** [comment]
単純にR=20とかの記入をするだけです。
カーブでの作図は不要です・・・
勾配とカーブは記入の必要があるのですが・・・どこか記載してましたっけ？

**Comment by isupport-kitta** [comment]
> シンプルにR=20とかの記入をするだけ です 。

ありがとうございます。
注記を付ける、表示するという意味でよいですか。
道路部境界のラインの作図は現状でよろしいですか。
レイヤーは何で作図しますか。

**Comment by yamamoto-ryuzo** [comment]
本日も、議会関係で時間が取れそうにありません。
明日は、大丈夫なはずなので今しばらくお待ち下しさい。

**Comment by isupport-kitta** [comment]
> 本日も、議会関係で時間が取れそうにはありません。 明日は、大丈夫なはずなので今しばらくお待ちください。

お返事ありがとうございます！
承知しました。

**Comment by yamamoto-ryuzo** [comment]
システムおよびマニュアルの更新を行いました。
ご確認ください。
![image](https://user-images.githubusercontent.com/86514652/207520410-b90f4dd9-15ec-4c29-aae8-c632479f58cd.png)
![image](https://user-images.githubusercontent.com/86514652/207520206-9b784347-4544-466a-9069-4ee77093d432.png)

**Comment by isupport-kitta** [comment]
道路線諸元レイヤ、作成ありがとうございます。
作図の仕方ですがこの方法で正しいのかわからなかったのでご指示ください。
道路の中心、及びカーブの中心と思われる位置から注記がある位置に向かって作図しました。
![image](https://user-images.githubusercontent.com/110583661/207536384-37af1b54-091c-46c2-bc95-8e00838b762a.png)


![image](https://user-images.githubusercontent.com/110583661/207536107-05df5dfc-98b7-4623-a9af-3068f6090015.png)

**Comment by isupport-kitta** [comment]
横断勾配について先ほどの2枚目の図面にある9％や12％が横断勾配だと思っていたのですが、違う感じでしょうか。
このように旗揚げされていた場合、旗揚げがある方が高いとかあるのでしょうか。
また、旗揚げの始点と終点に入力、中心に1箇所のみなど入力する箇所はどこにしたらよろしいですか。
ご指導いただけますと幸いです。

**Comment by yamamoto-ryuzo** [comment]
（上の平面）
曲線半径は　R=20　と　内容属性に入力して，片方は　内容なしでOKです。（側溝と同じ考え）
なので，曲線の　始まりと終わり２本線を引いてください。
（下の平面）
中心点は表示されない位置なので，同様に　R=30　と　内容属性に入力，これだけ離れると両方に入力してください。
　　　↑　マニュアル修正します。

**Comment by isupport-kitta** [comment]
![image](https://user-images.githubusercontent.com/110583661/207540382-3b62f700-0cc0-495d-a106-b0a625e78067.png)
![image](https://user-images.githubusercontent.com/110583661/207541053-051ea097-97c0-4a4a-b95f-3d02b7f0d3c0.png)
半径の中心側から引き直してみました。
曲線半径はこんな感じでよろしかったでしょうか

**Comment by yamamoto-ryuzo** [comment]
マニュアル更新しました。
![image](https://user-images.githubusercontent.com/86514652/207541956-3e347c7c-238c-477b-81a3-f0956495f8dd.png)

**Comment by yamamoto-ryuzo** [comment]
> 半径の中心側から引き直してみました。
> 曲線半径はこんな感じでよろしかったでしょうか

　R=○○　でお願いします。
　それ以外はそんな感じです。

**Comment by yamamoto-ryuzo** [comment]
> 横断勾配について先ほどの2枚目の図面にある9％や12％が横断勾配だと思っていたのですが、違う感じでしょうか。

これが縦断勾配です。

**Comment by isupport-kitta** [comment]
![image](https://user-images.githubusercontent.com/110583661/207542540-20eff261-362d-48cc-8432-5292e3e2af0e.png)
ありがとうございます。
内容の修正をしました。

**Comment by isupport-kitta** [comment]
> > 横断勾配について先ほどの2枚目の図面にある9％や12％が横断勾配だと思っていたのですが、違う感じでしょうか。
> 
> これが縦断勾配です。

あっててよかったです。
作図位置はどうしましょうか。

**Comment by yamamoto-ryuzo** [comment]
> 作図位置はどうしましょうか。

　曲線半径と同じく，始まりと終わりの引き出しおよび内容を示した線（テキストの上下向きが悪い場合は，反転してください。）です。
　
![image](https://user-images.githubusercontent.com/86514652/207544809-153a7a21-bc8d-4e37-ac42-9b15fa3e8536.png)

**Comment by yamamoto-ryuzo** [comment]
OKです。
再起動してもらうと矢印は無くなっていると思います。
先程更新したので。

**Comment by isupport-kitta** [comment]
ありがとうございます。
下図のように半径が小数点第一位まで記載があるときは内容は「R=8.0」と小数点第一位まで入力した方がよろしいですか。
![image](https://user-images.githubusercontent.com/110583661/207744508-8a412985-f7c7-493a-b2c3-835262fbb64c.png)

**Comment by yamamoto-ryuzo** [comment]
マニュアル追記しました。
基本，小数点第一位まで，ですが，既存はその精度が不明なので，既存のとおりでお願いします。
![image](https://user-images.githubusercontent.com/86514652/207775200-54db50e3-3a7c-4ed3-a2c5-67ef6987180a.png)

**Comment by yamamoto-ryuzo** [comment]
ごめんなさい。
i=8.0 で％不要です。

**Comment by isupport-kitta** [comment]
ありがとうございます。
既設道路の整備が終った図かく、全体的に作成しました。
曲線半径の注記について
内側にきたり外側にきたりしますがどちらにした方が良いなどありましたら見直しますのでお知らせください。現在はランダムで入力しています。

**Comment by yamamoto-ryuzo** [comment]
> 曲線半径の注記について
> 内側にきたり外側にきたりします

休日にお疲れ様です。
注記の位置は自動でその他の注記と重ならないように、スケールに応じて移動するようになっています。
他の注記もそれなりに動いています。
なので、起点●が中心側にあればOKです。

**Comment by isupport-kitta** [comment]
> > 曲線半径の注記について
> > 内側にきたり外側にきたりします
> 
> 休日にお疲れ様です。 注記の位置は自動でその他の注記と重ならないように、スケールに応じて移動するようになっています。 他の注記もそれなりに動いています。 なので、起点●が中心側にあればOKです。

返信ありがとうございます。
承知しました。
