### ISSUE TITLE
POSTGISへの管理データの移行について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#6]
（プロジェクトファイルについて）

1.　・・・・（管理者用）を利用ください。

　問題ないようなら，（管理者用）のカッコを削除し，統一したプロジェクトファイルにします。

　市道編入台帳はこちらで当面管理しますが，

　　　道路台帳平面図管理システム（管理者用）.qgs

　　　道路網図管理システム（管理者用）.qgs

　はアイサポートの都合のいいように，設定追加してもOkです。

　削除は注意してください。

2.その他のプロジェクトファイル

　道路網図管理システム（CNT-2018-102）.qgs

　等は，不要になり次第削除してください。

3.QGISの統合に向けた初期システム

　\\soja\総社市\QGIS\yr-qgis-portable-launcher

　の　QGIS.BAT　から起動してください。

　ポータブル版がインストールされます。

　順次カスタマイズしてゆきます。

　必要なプラグインがあれば，教えてください。

　システムバージョンアップの都合で，削除されるかもしれないので，システムに組み込みます。

4.今後の流れ

　アイサポート動作確認　＞　問題解消　＞　データベースに移行したデータの削除

　＞　その他データをデータベースへ格納

　の予定です。

　ご連絡お待ちしております。

**Comment by yamamoto-ryuzo** [comment]
現在、アイサポートによる　動作確認中です。
以前より安定したようなら、すべてのデータをPOSTGISへ移行するので　動作確認よろしくお願いします。

**Comment by isupport-kitta** [comment]
ありがとうございます。
本日2名で同時に入力作業を行いました。
ほぼ同時に更新することができました。
その後強制終了することもなく作業ができております。

**Comment by yamamoto-ryuzo** [comment]
念のため、同じ地物（同じラインととかです。）を同時更新した場合は、後から更新したデータが優先します。
そういったルールです。

**Comment by yamamoto-ryuzo** [comment]
10/29.30のいずれかでPOSTGISへ完全移行しようと思いますがどのような予定でしょうか。
ほぼそちらで作業されていても問題ないはずですが，念のため作業しない日に移行を予定しております。

**Comment by isupport-kitta** [comment]
ありがとうございます。
現在の使用の仕方でよろしければ問題なく作業出来ております。
明日、明後日とも作業をする予定にありませんので移行をお願いします。

**Comment by yamamoto-ryuzo** [comment]
完全移行しました。
以降の関係で，表示に予期せぬ変更があれば，それはエラーなので，教えて下さい。
