### ISSUE TITLE
側溝の種別について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#61]
市道台帳に「ス0.35」「ス0.3」と記載のある側溝があります。
この側溝の側溝種別をお知らせください。
![image](https://user-images.githubusercontent.com/110583661/207506065-e7601687-8461-4777-9a64-b1edd9d9d047.png)
![image](https://user-images.githubusercontent.com/110583661/207506176-31871e94-1594-4aaf-b921-dc653d408586.png)

写真で見ると石積の開渠のように見えます。
よろしくお願いします。

**Comment by yamamoto-ryuzo** [comment]
すぼりの「ス」と思われます。
開渠のU型でお願いします。
あまりたくさんあるようならまた教えて下さい。

**Comment by isupport-kitta** [comment]
ありがとうございます。
今まで整備してきて現在はこの1箇所だけです。
また出てきたらご連絡します。
