### ISSUE TITLE
QGIS起動のプレスリリース２０２２－１２－２１版　テスト依頼　

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#68]
QGISのプラグインを一般的な設置場所である，ユーザープロファイル内に移動しました。
テストによって入れ子ができて，適切にインストールできない場合があるようです。
　\\\\soja\総社市\QGIS\yr-qgis-portable-launcher
の
QGIS_pre.bat
から起動の上，動作報告よろしくお願いいたします。
エラーが無いようなら，正式版にします。
プラグインは下の表示が正解です。
![image](https://user-images.githubusercontent.com/86514652/208837850-d17c353a-15ca-449e-ad9e-ed75c92fad49.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。
起動、作業、問題なくできました。
プラグインのアイコンが少し違うようですが。。。仕様なんですかね
![image](https://user-images.githubusercontent.com/110583661/209024468-283eebd9-6382-4f1b-8ee8-e78094966db9.png)

**Comment by yamamoto-ryuzo** [comment]
私のプロファイルをコピーしたため，プラグインリローダーとデバッガーが入っています。
おおいのはOKです。
今後は，こちらで強制インストールするプラグインの関係で，この各自が追加したプラグインがこちらのバージョンアップにより自動削除されるので，よく使うプラグインは教えて下さい。
自動追加に追加しますので教えて下さい。
これから，リリースします。

**Comment by isupport-kitta** [comment]
実はちょっと以前よりなんですが起動するたびに起動前に下のような認証画面が出ていました。
![image](https://user-images.githubusercontent.com/110583661/209028685-76f09383-e45c-4f48-bf13-4f8d78c9de5e.png)
こちらの画面はQGIS_pre.batで起動しても出てきます。

**Comment by yamamoto-ryuzo** [comment]
confiファイルの更新をしてみました。
認証が無くなる予定です。
どうなったか教えてください。
実は，以前より私の環境は認証出てません・・・

**Comment by isupport-kitta** [comment]
> configファイルの更新をしてみました。 認証が無くなる予定です。 どうなったか教えてください。 実は，以前より私の環境は認証出てません・・・

ありがとうございます。
最初の立ち上げ時、configの配布メッセージが出ました。
それ以降は何も出ずに立ち上がるようになりました。
