### ISSUE TITLE
令和３年度　データの最終確認について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#7]
調書作成システムへのデータ引継ぎはパスコのほうで問題なかったようです。
中間ファイルのエクセルで修正した項目の、GISデータの反映の状況はどのようなかんじでしょうか。

　エクセルは修正したが、GISはそのままの状態が一番問題となる状態です。

問題点は、次年度の更新に向けてシステム改修予定です。
以上、報告お願いします。

**Comment by yamamoto-ryuzo** [comment]
昨年、時間がなかったので、こちらで絵だけ描いたところの後処理お願いしていたつもりなのですが、.１２月に告示したデータに更新されていないようです。
確認お願いします。
![image](https://user-images.githubusercontent.com/86514652/192120664-c8574831-2143-450c-a383-8dc329da7d1e.png)

**Comment by isupport-kitta** [comment]
お世話になります。
当該箇所（路線1037の区間41～49）の上記区間の近辺なのですが、道路が2本ある箇所だったかと記憶しております。
その際、幅員をどちらか片側の車線の幅員にするのか、2本の幅員+中央の法面の幅員も含むのかなどお聞きしたかと思います。（結局どうするのかわからないままそのままになってしまっているので、下記区間の「道路敷最大幅員」「道路敷最小幅員」「道路部最大幅員」「道路部最小幅員」の求め方（どの値になるのか）をご教授いただければ幸いです。
![image](https://user-images.githubusercontent.com/110583661/192191226-8419a1cc-79dc-4aa8-8db7-2675ad764632.png)
よろしくお願いいたします。

**Comment by yamamoto-ryuzo** [comment]
「道路敷最大幅員」「道路敷最小幅員」は敷地、つまり道路区域なので、黄色の線で最大値と最小値です。
「道路部最大幅員」「道路部最小幅員」は道路部、つまり車道部分ですが、今回、ややこしいことに、同一断面に道路が2本、いわゆるなんでもない道路区域で分割されており、道路部幅員として記載している4.6（4.6）とかの寸法の最大幅、最小幅を確認ください。
路線が長いので、既存の数値と比べて、今回修正した数値がどうなのかで判断していただければOKです。

なので、既存の最大幅員と最小幅員の間に今回修正した数値があれば変わらないことになります。

![image](https://user-images.githubusercontent.com/86514652/192213606-44149fe0-205f-4c24-be98-1eb30f5c408a.png)

**Comment by isupport-kitta** [comment]
例えば上の区間４１であれば
道路敷最大幅員30.4m　道路敷最小幅員4.6m
道路部最大幅員15.2m　道路部最小幅員4ｍ
ということになりますでしょうか。

**Comment by yamamoto-ryuzo** [comment]
区間41はそれでOKです。

**Comment by isupport-kitta** [comment]
その他の道路敷幅員が入力されていない区間はnullでしょうか
計測値を入力でしょうか

**Comment by isupport-kitta** [comment]
計測値を入力しました。面積等は問題ないようです。
一度ご確認よろしくお願いします。

**Comment by isupport-kitta** [comment]
2021/12/28の取得日のものを確認したところ、道路台帳入力シートは更新した（幅員や面積を修正した）がQGIS上の基本情報は値が入っていない箇所がありました。（42-3066路線C4-41区間２～７、42-3079路線C4-41区間6～10など）

この場合、QGIS上で値の修正をしたらよろしいですか。

**Comment by yamamoto-ryuzo** [comment]
2021/12/28は、時間がなかったので事実上告示の集計も人力で行っております。
必要最低限の絵だけがあると思ってください。
なので、基本情報も取得日が2021/12/28でない、当初のものは一度、消去年月日を入力し、非表示状態にしてください。
その後、2021/12/28の情報を入力お願いします。
俗にいう、通常の作業です。

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/7#issuecomment-1258771552
について
通常の入力同様必要です。
でないと、敷地面積が算出できないと思います。
![image](https://user-images.githubusercontent.com/86514652/192657697-057fe430-46c7-4f40-abea-b116d5f7bfff.png)

**Comment by yamamoto-ryuzo** [comment]
### **重要**
https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/7#issuecomment-1258976217
について
取得年月日が　2021-04-08　は当初のデータです。
更新があったので、このデータは一度　2021-12-28 で、消去年月日が入って終了。

更新後のデータは、取得年月日が　2021-12-28　となるはずですが？

他の修正もそうしてますよね？
　
![image](https://user-images.githubusercontent.com/86514652/192658743-ed4f2d31-de31-41df-9c32-0dd14e6030fa.png)

**Comment by isupport-kitta** [comment]
はい、まず当初のデータを2021/04/08で作成して2022/03/31や2021/12/28で消去日を入れて新しい道路をその日時で取得日としてます。

**Comment by yamamoto-ryuzo** [comment]
了解しました。

**Comment by isupport-kitta** [comment]
1037路線の図面番号D4-15、区間41～49が当初の基本情報になってしまっているのを確認しました。
一度消去年月日を入力して全て非表示にし、新規で道路基本情報を入れなおします。
この際、道路基本情報の形状としては新旧どちらの道路中央線に作成したらよろしいですか。
（現在の道路基本情報は旧道路の中央線を通って作図されています。）
もしくは区域の中央辺りを取って区域境界の中央線に作図がよろしいですか。

**Comment by yamamoto-ryuzo** [comment]
道路中心線はあくまで道路の中心です。
区域の中心線は存在しません。
1037路線の図面番号D4-15、区間41～49 は、ともあった道路が本線と考えており、作図もそういった作図にしています。
なので、現在の基本情報をそのまま複写していただき、必要箇所の属性を変えていただければと思います。
![image](https://user-images.githubusercontent.com/86514652/192928165-5d728355-df9f-424e-9c6e-34b368ece011.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。
1037路線の図面番号D4-15、区間41～49が2021/04/08取得の道路基本情報だったのを2021/12/28取得のものを作成しました。
また、2021/12/28取得日のデータに関しまして現在確認を進めています。

"\\soja\総社市\更新データ\20211228取得データ確認一覧.xlsx"
上記Excelの着色部分がちゃんとデータが入っていなかった箇所です。
これと道路台帳入力シートを見ながらQGISにて修正を行っていきます。

**Comment by yamamoto-ryuzo** [comment]
すべてのR3データの最終確認（見直し）は完了しましたでしょうか？
完了後は、実績報告書を修正のうえ一度提出ください。
　総社市道路台帳補正実施報告書（入札業者）.xlsx
集計は「納品年月日」を入力の上、集計してください。
例）「納品年月日」右下
![image](https://user-images.githubusercontent.com/86514652/195232825-dd8aa465-df56-4251-925e-213181b76a36.png)

**Comment by nagasawajun** [comment]
山本竜三さま
R03について、現地調査を行ってから数量を取りまとめようと思います。
12月中を目途に、結果のご報告でよろしいでしょうか。

**Comment by city-soja-chiiki** [comment]
R03については、現地調査不要です。
すでに、確定しているので。
また、明らかに、CADデータ及び他の資料から不要と思われるものも、適宜判断の上、現地調査を行ってください。
以上。

**Comment by nagasawajun** [comment]
承知いたしました。
R03について、現地調査0で
実施数量が計87.915人となるようにして報告書を作成いたします。
報告書作成後、ご報告いたします。

ちなみにR04業務は、実施数量116.4人が目標になりますでしょうか。
単価精算としたら、少なくなっても大丈夫なのでしょうか。
（今日時点でR03業務の実施数量をようやく満たしたのかなという感じです。）

**Comment by yamamoto-ryuzo** [comment]
単価契約なので、極力全数実施となるように
「道路台帳平面図（修正）電子化のみ」の実施数量で調整の予定です。
以上。

**Comment by nagasawajun** [comment]
返信ありがとうございます。
極力全数実施について、承知いたしました。

**Comment by yamamoto-ryuzo** [comment]
本件は，現地調査なしの，精査をお願いしておりますが，いつ頃「令和３年度　データの最終確認」出来そうでしょうか。

**Comment by nagasawajun** [comment]
対応遅れており、申し訳ございません。
来週中にはご報告予定です。

**Comment by nagasawajun** [comment]
\\soja\総社市\市役所⇔アイ・サポート\報告書（仮）
総社市道路台帳補正実施報告書（入札業者）.xlsx

上記に数量を取りまとめましたので、ご確認お願いいたします。
実施報告書 (R4清算)シート：最終の数量です。
路線認定シート：精算数量の根拠です。
2021 12シート：第4章平面図（修正）作成数量の根拠です。（2021/12/28）
2022 03シート：第4章平面図（修正）作成数量の根拠です。（2022/3/31）

**Comment by yamamoto-ryuzo** [comment]
報告書も簡易に作成できるようにエクセル化が必要なようです。
とりあえず，いただいたエクセルをもとに
総社市道路台帳補正実施報告書（入札業者）修正案.xlsx
として，作成していこうと思ったのですが，併せ入力チェックもできる様式に変更しようと思います。

**Comment by yamamoto-ryuzo** [comment]
路線数の確認
![image](https://user-images.githubusercontent.com/86514652/199484361-4d0f9920-1e85-4c59-9a0b-f767cbb342f7.png)
となります。
![image](https://user-images.githubusercontent.com/86514652/199484300-08b18c05-a0bd-42a1-b153-d0f4b90d3180.png)
が原因と思われます。
確認お願いします。

**Comment by yamamoto-ryuzo** [comment]
供用開始の番地
供用開始しているにも関わらず，入力されていません。
供用開始の報告書作成時にGISに入力したのちに，その情報を使ってくれていますでしょうか。
以前にも，確認しましたが，ＧＩＳ入力＞エクセルへ属性貼り付け＞書類作成です。

![image](https://user-images.githubusercontent.com/86514652/199485279-b0fb5b19-074d-48ea-a6c3-b5145510414a.png)

**Comment by nagasawajun** [comment]
ご指摘の件、申し訳ございません。確認しまして、再度お返事いたします。

**Comment by isupport-kitta** [comment]
> 路線数の確認 ![画像](https://user-images.githubusercontent.com/86514652/199484361-4d0f9920-1e85-4c59-9a0b-f767cbb342f7.png) となります。 ![画像](https://user-images.githubusercontent.com/86514652/199484300-08b18c05-a0bd-42a1-b153-d0f4b90d3180.png) が原因と思われます。 確認お願いします。

お世話になにます。確認いたしました。
ご指摘の通り61-3031路線に不要な作図が1件重複して入っておりました。
消去年月日に日時は入っておりましたが、不要（作図のミス）として地物（id:4956）そのものを削除いたしました。
![image](https://user-images.githubusercontent.com/110583661/199855318-9681a729-d063-48bf-a7ec-4f84e8621007.png)

**Comment by yamamoto-ryuzo** [comment]
供用開始区間の起終点は，そもそも18条網図の整備を開始した時点で「必要か？」という疑義もあるので，一応，何のための項目かパスコに問い合わせてみます。
実際，パスコもデータがない以上，ほかの手法で管理しているのかもしれません。

しばらくお待ちください。

**Comment by isupport-kitta** [comment]
> 供用開始区間の起終点は，そもそも18条網図の整備を開始した時点で「必要か？」という疑義もあるので，一応，何のための項目かパスコに問い合わせてみます。 実際，パスコもデータがない以上，ほかの手法で管理しているのかもしれません。
> 
> しばらくお待ちください。

ありがとうございます。
Excelに張り付ける際に起点住所、終点住所で資料を作成していましたので、新設路線において供用開始区間は起終点と同じになると理解しておりました。申し訳ありません。
一応、現在供用になっている路線は供用開始区間起終点に住所を入力いたしました。
10-3649～10-3653の路線は供用開始されておりませんので空欄にしております。
![image](https://user-images.githubusercontent.com/110583661/199859136-3862b9de-3a01-4bf1-953f-c527edde47e1.png)

**Comment by yamamoto-ryuzo** [comment]
入力，確認いたしました。
「必要か？」につきましては，前述のとおり今しばらくお待ちください。
