### ISSUE TITLE
既設道路整備:問合せ　道路基本情報の作図について

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#71]
路線番号 10-3204　図郭 E5-132　区間番号0100
下図のように道路内に車道以外がある箇所では道路基本情報はどのように作図したらよろしいですか。
現在は区間の前後の区割線の中央で結んでいます。
![image](https://user-images.githubusercontent.com/110583661/209246108-828fe0ad-4ab3-4051-bd88-1931ac672d25.png)

**Comment by yamamoto-ryuzo** [comment]
細かく言うと本来は，常に道路基本情報と道路断面は90°となるはずです。
なぜなら中心線の直角方向が道路断面だからです。

しかし，なかなか起点などはそうはならないので，なかなか直角になりにくいです。

この個所に限定すると
![image](https://user-images.githubusercontent.com/86514652/209246771-2a6f5841-2ab1-4f91-a59a-febceaf80d1b.png)
の
![image](https://user-images.githubusercontent.com/86514652/209246804-60aba6d7-bb1c-4f8b-be29-e11a12c3f712.png)
の向きが中心線の方向なので，一度そっちに向いて適当に戻っていくような道路基本情報線となります。

**Comment by isupport-kitta** [comment]
ありがとうございます。下図のような形で大丈夫そうですか
台帳の延長と大きく（1m以上）違ってきてしまいます。
![image](https://user-images.githubusercontent.com/110583661/209271132-1b914592-bce5-4ccf-8168-bfd326c01e0b.png)

**Comment by yamamoto-ryuzo** [comment]
本来は、道路中心線は本体、連続した線です。
1.一番下の線が測定時の線に近いのだと思います。
　で道路方向はなるべく現実に合わせた折衷案になったのかと？
2.折衷案で線と書くと、真ん中の線です。
3.今更の線なので、一番上でもOKです。
少なくとも現在の線は、確かに誤差が大きすぎるので、既存が正しいの精神でお願いします。
![image](https://user-images.githubusercontent.com/86514652/209312192-bfba23cf-e687-4c89-8cd2-1175e81982a6.png)

現在、180号でいろいろ苦慮されていると思いますが、あまり細かくとると結構大変なので、慣れてくるとこのくらいいい加減に分割できるようになるという、ある意味いい見本です。

**Comment by isupport-kitta** [comment]
ありがとうございます。修正しました。
![image](https://user-images.githubusercontent.com/110583661/214795249-759ccf64-a569-4e4c-a9f4-ca06f4290669.png)
