### ISSUE TITLE
令和4年度　3月議会　議案修正

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#79]
地域応援課　三宅

お世話になっております、3月議会議案の修正依頼です。

10-3665　総社支線3665号道　起点変更　総社市　総社４番2地先　→　総社4番7地先
60-3052　西郡支線3052号道　起点変更　総社市　西郡1461番1地先　→　西郡1461番3地先

修正よろしくお願いします。

**Comment by isupport-kitta** [comment]
お世話になります。
\\soja\総社市\更新データ\議案用\R04\3月議会
Excel及びPDFの修正をしました。
確認をよろしくお願いします。
![image](https://user-images.githubusercontent.com/110583661/211958309-dfd181df-e4a2-4fa8-b7c6-03f2f382daa9.png)
![image](https://user-images.githubusercontent.com/110583661/211958341-d413be82-ee80-49b4-91ee-08c37ed49a12.png)
![image](https://user-images.githubusercontent.com/110583661/211958369-d4b19941-b8b0-4568-bf44-0ea8e2c52358.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
参考に使ってください
[IMG_20230120_0001.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10463370/IMG_20230120_0001.pdf)

**Comment by isupport-kitta** [comment]
お世話になります。
180号バイパス関連の告示○○号.pdf及びエクセルを修正いたしました。
"\\soja\総社市\更新データ\議案用\R04\180号関連\【原本】R05-01-29　区域決定・供用開始　告示○○号20230123.pdf"
"\\soja\総社市\更新データ\議案用\R04\180号関連\【原本】R05-01-29　区域決定・供用開始　告示○○号20230123.xls"

**Comment by city-soja-chiiki** [comment]
修正ありがとうございました。
確認します。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
区域決定の中に区域変更の内容がコピーされたままになっています。

![スクリーンショット 2023-01-23 123437](https://user-images.githubusercontent.com/110579656/213961932-a218e0a8-1467-4a94-beb8-0cb94c2dc0a0.png)


10-3227　10-3232　10-3288　10-3283
4路線

**Comment by isupport-kitta** [comment]
区域変更の内容と区域決定の内容と違うという意味でしょうか。
18条管理網図内の幅員の確認をします。

**Comment by yamamoto-ryuzo** [comment]
区域決定
　前　のところに数値は入らないものです。
　初めて，その区間を決定するのだから　数値はないはずです。
↓の路線も，前の絵がないことないです。つまり初めて。
![image](https://user-images.githubusercontent.com/86514652/213963829-344858d0-ba65-488c-b79f-04726080f30b.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。修正しました。ご確認よろしくおねがいします。

また、10-3227の最大幅員も重用区間のものが入っていたので修正しました。
![image](https://user-images.githubusercontent.com/110583661/213965584-26c9c702-2a9a-4190-9679-2cb868699561.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
最小幅員の確認お願いします。
10-3663　4.0ｍでは
10-5197　4.5ｍでは
10-3288　4.0ｍでは
10-3283　4.6ｍでは　延長　94.6ｍでは

![スクリーンショット 2023-01-23 163537](https://user-images.githubusercontent.com/110579656/213988962-164e5dd5-29d2-4fe2-8529-06de7152a152.png)
![スクリーンショット 2023-01-23 164006](https://user-images.githubusercontent.com/110579656/213988976-bd8c4168-a94b-46f1-b5c2-ec1f883ebccb.png)

**Comment by isupport-kitta** [comment]
区域幅員、区域境界線のみ表示しています。10-3663は4.4でよろしいですか。
![image](https://user-images.githubusercontent.com/110583661/213999104-45fc2589-714f-4052-90f1-6f7542af0aac.png)

**Comment by isupport-kitta** [comment]
10-5197路線について
区域最小幅員は図の位置で5.0で取っていますが4.5の箇所を見つけることができませんでした。
どのあたりになりますでしょうか（区域幅員、区域境界線のみ表示しています。）
![image](https://user-images.githubusercontent.com/110583661/213999917-c707bda6-4483-4ec4-a270-6b69ad3a94b8.png)

**Comment by isupport-kitta** [comment]
10-3288路線について
区域最小幅員は図の位置で4.8で取っていますが4.0の箇所を見つけることができませんでした。
どのあたりになりますでしょうか（区域幅員、区域境界線のみ表示しています。）
![image](https://user-images.githubusercontent.com/110583661/214000579-152205f4-ed23-4cfe-accb-1dbb27992e7a.png)

**Comment by isupport-kitta** [comment]
10-3283路線について
延長は94.6mに修正しました。
5.0で取っていますが4.6の箇所を見つけることができませんでした。
どのあたりになりますでしょうか（区域幅員、区域境界線のみ表示しています。）
![image](https://user-images.githubusercontent.com/110583661/214001652-027d9821-69a0-48bd-8e69-5b2385bf6139.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
修正済です。
