### ISSUE TITLE
LGWANとクラウド環境のシステム統合について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#8]
統合についてですが、現在はクラウドのQGISは汎用品を使用しております。
　この汎用品を検索機能・起動方法をLGWANと統合するため、たぶん、専用システムに近しい状態になります。

　また、現在、QGISのバージョンがいろいろあると、実はプロジェクトファイルの構造が微妙にバージョンごとに変わるので、動作エラーが発生しやすくなります。
　最近では3.1＞3.16で複雑なシンボロジを再作成する事案もありました。

　ということで、いまのところはその方向だという認識でお願いします。
　当然、作業によって現在のような独自ファイルの作成は全くもんだありません。

　統合の具体的順番としては

　1.LGWANのオープンソース化
　2.LGWANとクラウドのQGIS環境の統一
　3.クラウドにおける統一環境の提供
　4.QGIS環境の維持管委託
　　　維持管理にはLGWANおよびクラウドの
　　　　　　　　　　　　　QGISの定期バージョンアップ
　　　　　　　　　　　　　プロジェクトファイルの維持管理

　現在。1.LGWANのオープンソース化　のシステムの初期版が出来上がったところです。
　QGIS.BATの起動はできましたでしょうか？

　下記の「3.QGISの統合に向けた初期システム」です。
　https://github.com/city-soja-chiiki/douro_daityou_hosei/issues/6

**Comment by yamamoto-ryuzo** [comment]
現在，2.LGWANとクラウドのQGIS環境の統一　が完了しております。
3.クラウドにおける統一環境の提供　を検討しております。

常時，利用するかどうかは別にして，内容確認は，この統一環境で動くかどうかということになるので，クラウド環境がそのまま，アイ・サポートのローカル環境でも動いたかどうか確認の上，返信ください。

**Comment by isupport-kitta** [comment]
ご連絡ありがとうございます。
LGWANとクラウドのQGIS環境の統一が完了しているとのことですが、
具体的な状況が把握できておらず、クラウド環境がアイサポートのローカル環境でも動いたかをどのように確認するのか
まだ理解できておりません。
アイサポートサーバ上のみで現在のQGISバージョンが動作するかの確認をすればよろしいでしょうか。
お手数おかけしますが、詳細な状況と作業内容を確認させてください。

**Comment by yamamoto-ryuzo** [comment]
\\soja\総社市\QGIS\yr-qgis-portable-launcher
から　QGIS.BAT　を起動したら。
下記のような画面が立ち上がるのが正解です。
ｃ：￥ドライブに余裕が必要です。
内容なら調整します。
![image](https://user-images.githubusercontent.com/86514652/192211428-de837a9e-60b4-4f49-993e-5332e3a058e9.png)

**Comment by isupport-kitta** [comment]
ありがとうございます。無事上記画面は立ち上がりました。
![image](https://user-images.githubusercontent.com/110583661/192399947-4a3629de-2b7a-46b4-bce4-3071a59ed40a.png)

**Comment by yamamoto-ryuzo** [comment]
とりあえず、下記赤丸内は削除してもよろしいでしょうか。
![image](https://user-images.githubusercontent.com/86514652/192409435-1ad4ee9e-3251-4ed7-a840-7b258bf53ca2.png)

**Comment by isupport-kitta** [comment]
はい、大丈夫です。
よろしくお願いします。

**Comment by yamamoto-ryuzo** [comment]
削除しました。
作業用とQGZファイルは使い方が定まるまで残しておきます。
