### ISSUE TITLE
１０－３４１１　終点側

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#87]
![image](https://user-images.githubusercontent.com/86514652/213107431-a3f04c6f-13e9-470f-9f40-613e0268e9db.png)
段差あるのおかしいので現地確認して連絡します。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
修正お願いします。
[10-3411　福井支線3411.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10463098/10-3411.3411.pdf)

**Comment by isupport-kitta** [comment]
平面図の修正をしました。確認をお願いします。
![image](https://user-images.githubusercontent.com/110583661/213635507-b9d96f11-45c1-4ab9-b1d0-ae28e076a47c.png)

**Comment by city-soja-chiiki** [comment]
暗渠から開渠に断面変わりしているため、水路と道路部境界が逆になっているため修正おねがいします
![ttt-01](https://user-images.githubusercontent.com/110579656/213643833-36577ab6-f0e4-4f81-875a-28aa865ca1f6.png)

**Comment by isupport-kitta** [comment]
ご確認ありがとうございます。修正しました。
![image](https://user-images.githubusercontent.com/110583661/213655071-026623a7-2f3e-44b3-871a-e4db0baebbaa.png)
![image](https://user-images.githubusercontent.com/110583661/213655192-8d8a870b-1349-4f13-92f5-12cd6bbdbe20.png)

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
修正ありがとうございました。
