### ISSUE TITLE
10-3545

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_daityou_hosei#95]

**Comment by yamamoto-ryuzo** [comment]
![image](https://user-images.githubusercontent.com/86514652/213113232-ea063115-7e11-4235-b78f-7d6d04004a53.png)
道路センターの変更
網図も変更
区域も変更

**Comment by isupport-kitta** [comment]
道路法18条管理網図及び路線認定（路線網図）の修正
道路線形諸元追加、区割り位置見直し、道路基本情報の修正を行いました。
確認よろしくお願いします。
![image](https://user-images.githubusercontent.com/110583661/213350290-bd52ae20-6306-4b24-94a2-fb6491f5ce7c.png)
