### ISSUE TITLE
3月議会　新規路線認定

### ISSUE THREAD

**Issue by city-soja-chiiki** [city-soja-chiiki/douro_daityou_hosei#98]

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅

お世話になっております。
3月議会の追加です。

新規3000番市道　　起点　総社市　総社1647番1地先　　終点　総社市　井手1189番1地先

よろしくお願いします。
[10-3309 総社支線3309号道.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10452338/10-3309.3309.pdf)

**Comment by isupport-kitta** [comment]
お世話になります。
上記道路の〈道路計画等の内容〉は・指定道路　・開発道路　・新設道路のどれになりますでしょうか
いったん、新設道路で作成しておきます。

**Comment by city-soja-chiiki** [comment]
新規道路でお願いします。

**Comment by isupport-kitta** [comment]
新設道路でよろしいですか
![image](https://user-images.githubusercontent.com/110583661/213336140-8653b49e-78da-4248-abfc-dd82efd8146b.png)

**Comment by isupport-kitta** [comment]
エクセル及びPDFを修正しました。確認をお願いします。
\\soja\総社市\更新データ\議案用\R04\3月議会
議案第○○号　市道の路線認定・変更・廃止について.pdf
![image](https://user-images.githubusercontent.com/110583661/213336406-dd777e52-b871-4c57-93a6-b76c791ff058.png)
路線認定(位置図) .pdf
![image](https://user-images.githubusercontent.com/110583661/213336480-933f5f30-7372-4d36-b844-2ba3c5da6892.png)

**Comment by city-soja-chiiki** [comment]
新設道路でした。
Excelありがとうございます。
