### ISSUE TITLE
路線認定適応外（路線網図）_新規発番時

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/douro_daityou_hosei#99]
道路の種類に4000番台と4500番台とありますがどちらで発番すればよろしいでしょうか
また、4000番台と4500番台の違いはどこで見分けたらよろしいでしょうか。
![image](https://user-images.githubusercontent.com/110583661/213337471-715b6baf-7f93-402d-8031-973f54ac958d.png)

**Comment by yamamoto-ryuzo** [comment]
![image](https://user-images.githubusercontent.com/86514652/213386059-7d8febd5-a8fa-4097-8d15-2bcafdb149e0.png)
どちらになるのか別途指示します。
今しばらくお待ちください。

**Comment by isupport-kitta** [comment]
回答ありがとうございます。
ご指示お待ちします。

**Comment by city-soja-chiiki** [comment]
地域応援課　三宅
農道4000・4500番台の発番です。
よろしくお願いします。

[新規4000・4500農道1.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10462148/4000.4500.1.pdf)
[新規4000・4500農道2.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10462149/4000.4500.2.pdf)
[新規4000・4500農道3.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10462151/4000.4500.3.pdf)
[新規4000・4500農道4.pdf](https://github.com/city-soja-chiiki/douro_daityou_hosei/files/10462153/4000.4500.4.pdf)

CADデータは下記のファイルに入れています。
施設台帳→R5.1.10国道180BP水路網図

**Comment by isupport-kitta** [comment]
ありがとうございます。入力が終わりました。ご確認をお願いします。
![image](https://user-images.githubusercontent.com/110583661/213598820-eec83148-7492-4668-ae54-39c3d9705a18.png)

**Comment by city-soja-chiiki** [comment]
内容確認しました。
上記内容でOKです。

**Comment by isupport-kitta** [comment]
ありがとうございます。クローズします。
